
INSERT INTO bus (nom_long, ligne)
VALUES
  ('Parcelles Assainies', 'Ligne 1'),
  ('Corniche (U 10-9-15)', 'Ligne 1'),
  ('Dior', 'Ligne 1'),
  ('Acapes', 'Ligne 1'),
  ('Dispensaire Norade', 'Ligne 1'),
  ('Passage entre U22 et U24', 'Ligne 1'),
  ('Marché Grand-Médine', 'Ligne 1'),
  ('VDN', 'Ligne 1'),
  ('Relais', 'Ligne 1'),
  ('Avenue Cheikh Anta Diop', 'Ligne 1'),
  ('Avenue Blaise Diagne', 'Ligne 1'),
  ('Avenue Jean Jaurès', 'Ligne 1'),
  ('Avenue André Peytavin', 'Ligne 1'),
  ('Avenue George Pompidou', 'Ligne 1'),
  ('Place de l’Indépendance', 'Ligne 1'),
  ('Allées Canard', 'Ligne 1'),
  ('Esso Port', 'Ligne 1'),
  ('Embarcadère', 'Ligne 1'),
  ('Place Leclerc', 'Ligne 1'),
  ('Liberté 5', 'Ligne 4'),
  ('Place Leclerc', 'Ligne 4'),
  ('Terminus Dieuppeul', 'Ligne 4'),
  ('Cité Derklé', 'Ligne 4'),
  ('Khar Yalla', 'Ligne 4'),
  ('Cité Marine', 'Ligne 4'),
  ('CEG Dieuppeul 3', 'Ligne 4'),
  ('Camp Sapeurs-Pompiers', 'Ligne 4'),
  ('Cité Sacré Cœur', 'Ligne 4'),
  ('Collège Sacré Cœur', 'Ligne 4'),
  ('Sicap Karack', 'Ligne 4'),
  ('Avenue Bourguiba', 'Ligne 4'),
  ('Dial Diop ex rue 10', 'Ligne 4'),
  ('Point E', 'Ligne 4'),
  ('HLM Fass', 'Ligne 4'),
  ('Canal Gueule Tapée', 'Ligne 4'),
  ('Avenue Blaise Diagne', 'Ligne 4'),
  ('Avenue Jean Jaurès', 'Ligne 4'),
  ('Boulevard de la République', 'Ligne 4'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 4'),
  ('Allées Canard-Esso Port Embarcadère', 'Ligne 4'),
  ('Terminus Leclerc', 'Ligne 4'),
  ('Ouakam', 'Ligne 7'),
  ('Palais 2', 'Ligne 7'),
  ('Terminus Ouakam', 'Ligne 7'),
  ('Cité Assemblée', 'Ligne 7'),
  ('Comico', 'Ligne 7'),
  ('Av Cheikh Anta Diop (route de Ouakam)', 'Ligne 7'),
  ('avenue Blaise Diagne', 'Ligne 7'),
  ('avenue Jean Jaurès', 'Ligne 7'),
  ('avenue André Peytavin', 'Ligne 7'),
  ('Avenue Georges Pompidou', 'Ligne 7'),
  ('Place de l’Indépendance', 'Ligne 7'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 7'),
  ('Avenue Nelson Mandela', 'Ligne 7'),
  ('Palais de Justice', 'Ligne 7'),
  ('Aéroport LSS', 'Ligne 8'),
  ('Palais 2', 'Ligne 8'),
  ('Terminus Aéroport', 'Ligne 8'),
  ('Cité Asecna', 'Ligne 8'),
  ('Yoff Village', 'Ligne 8'),
  ('Stade Léopold Sédar Senghor', 'Ligne 8'),
  ('Patte d’Oie', 'Ligne 8'),
  ('Grand Yoff', 'Ligne 8'),
  ('Cité des Eaux', 'Ligne 8'),
  ('Avenue Bourguiba', 'Ligne 8'),
  ('Rue Dial Diop (ex rue 10)', 'Ligne 8'),
  ('Zone B', 'Ligne 8'),
  ('Rocade Fann Bel Air (Point E)', 'Ligne 8'),
  ('Avenue Cheikh Anta Diop (Cité Universitaire)', 'Ligne 8'),
  ('Avenue Blaise Diagne', 'Ligne 8'),
  ('Avenue Jean Jaurès', 'Ligne 8'),
  ('Bld de la République', 'Ligne 8'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 8'),
  ('Avenue Nelson Mandela', 'Ligne 8'),
  ('Palais de Justice', 'Ligne 8'),
  ('Liberté 6', 'Ligne 9'),
  ('Palais 2', 'Ligne 9'),
  ('Liberté 6', 'Ligne 9'),
  ('Sacré Cœur', 'Ligne 9'),
  ('Terminus Dieuppeul', 'Ligne 9'),
  ('Allées Ababacar Sy', 'Ligne 9'),
  ('Rondpoint Jet d’Eau', 'Ligne 9'),
  ('Allées Cheikh Sidate (Niary Tally)', 'Ligne 9'),
  ('Eglise Sainte Thérèse', 'Ligne 9'),
  ('Avenue Dial Diop (ex rue 10)', 'Ligne 9'),
  ('Bld Général De Gaule', 'Ligne 9'),
  ('Avenue Malick Sy', 'Ligne 9'),
  ('Avenue Blaise Diagne', 'Ligne 9'),
  ('Avenue Jean Jaurès', 'Ligne 9'),
  ('Avenue André Peytavin', 'Ligne 9'),
  ('Avenue Pompidou', 'Ligne 9'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 9'),
  ('Avenue Nelson Mandela', 'Ligne 9'),
  ('Palais 2', 'Ligne 9'),
  ('Liberté 5', 'Ligne 10'),
  ('Palais 2', 'Ligne 10'),
  ('Terminus Dieuppeul', 'Ligne 10'),
  ('Cité Derklé', 'Ligne 10'),
  ('Khar Yalla', 'Ligne 10'),
  ('Cité Marine', 'Ligne 10'),
  ('CEG Dieuppeul 3', 'Ligne 10'),
  ('Eglise Martyrs de l’Ouganda (rue 11 x P)', 'Ligne 10'),
  ('Stade Marius Ndiaye', 'Ligne 10'),
  ('Avenue Bourguiba', 'Ligne 10'),
  ('Relais', 'Ligne 10'),
  ('Avenue Cheikh Anta Diop', 'Ligne 10'),
  ('Rue Aimé Césaire', 'Ligne 10'),
  ('Corniche Ouest', 'Ligne 10'),
  ('Village Artisanal de Soumbédioune', 'Ligne 10'),
  ('Prison Central', 'Ligne 10'),
  ('Bld de la République', 'Ligne 10'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 10'),
  ('Avenue Nelson Mandela', 'Ligne 10'),
  ('Palais 2', 'Ligne 10'),
  ('Dieuppeul', 'Ligne 18'),
  ('Centre-ville', 'Ligne 18'),
  ('Dieuppeul', 'Ligne 18'),
  ('Terminus Dieuppeul', 'Ligne 18'),
  ('Cité Derklé', 'Ligne 18'),
  ('Khar Yalla', 'Ligne 18'),
  ('Cité Marine', 'Ligne 18'),
  ('Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)', 'Ligne 18'),
  ('Station Castors', 'Ligne 18'),
  ('Cité Port', 'Ligne 18'),
  ('Rocade Fann Bel Air', 'Ligne 18'),
  ('Colobane', 'Ligne 18'),
  ('Police Bel Air', 'Ligne 18'),
  ('Grand Moulin de Dakar', 'Ligne 18'),
  ('Quai de pêche', 'Ligne 18'),
  ('Esso Port', 'Ligne 18'),
  ('Place de l’Indépendance', 'Ligne 18'),
  ('Avenue Georges Pompidou', 'Ligne 18'),
  ('Avenue André Peytavin', 'Ligne 18'),
  ('Route de la Corniche', 'Ligne 18'),
  ('Avenue Malick Sy', 'Ligne 18'),
  ('Rue 6', 'Ligne 18'),
  ('Gueule Tapée', 'Ligne 18'),
  ('Lycée Delafosse', 'Ligne 18'),
  ('Avenue Cheikh Anta Diop', 'Ligne 18'),
  ('Ecole Normale Supérieure', 'Ligne 18'),
  ('Avenue Bourguiba', 'Ligne 18'),
  ('Rond-Point Jet d’eau', 'Ligne 18'),
  ('Allées Ababacar Sy', 'Ligne 18'),
  ('Terminus Dieuppeul', 'Ligne 18'),
  ('Dieuppeul', 'Ligne 20'),
  ('Centre-ville', 'Ligne 20'),
  ('Dieuppeul', 'Ligne 20'),
  ('Terminus Dieuppeul', 'Ligne 20'),
  ('Allées Ababacar Sy', 'Ligne 20'),
  ('Jet d’eau', 'Ligne 20'),
  ('Avenue Bourguiba', 'Ligne 20'),
  ('Ecole Police (Relais)', 'Ligne 20'),
  ('Avenue Cheikh Anta Diop', 'Ligne 20'),
  ('Hôpital Fann', 'Ligne 20'),
  ('Cité Universitaire', 'Ligne 20'),
  ('Lycée Delafosse', 'Ligne 20'),
  ('HLM Gueule Tapée', 'Ligne 20'),
  ('Rue 6', 'Ligne 20'),
  ('Avenue Malick Sy', 'Ligne 20'),
  ('Corniche Ouest', 'Ligne 20'),
  ('Avenue Peytavin', 'Ligne 20'),
  ('Avenue Pompidou', 'Ligne 20'),
  ('Place de l’Indépendance', 'Ligne 20'),
  ('Esso Port', 'Ligne 20'),
  ('Bld de l’Arsenal', 'Ligne 20'),
  ('Central Bel Air (MTOA)', 'Ligne 20'),
  ('Grands Moulin de Dakar', 'Ligne 20'),
  ('Police Bel Air', 'Ligne 20'),
  ('Colobane', 'Ligne 20'),
  ('Angle Colobane', 'Ligne 20'),
  ('Rue 13 prolongée', 'Ligne 20'),
  ('Station Castors', 'Ligne 20'),
  ('Avenue Cheikh Ahmadou Bamba', 'Ligne 20'),
  ('Cité Port', 'Ligne 20'),
  ('Ouakam', 'Ligne 23'),
  ('Village Des Pêcheurs', 'Ligne 23'),
  ('Terminus Ouakam', 'Ligne 23'),
  ('Yoff', 'Ligne 23'),
  ('Corniche Est', 'Ligne 23'),
  ('Avenue Malick Sy', 'Ligne 23'),
  ('Avenue de la Somme', 'Ligne 23'),
  ('Sacré Cœur 1', 'Ligne 23'),
  ('Sacré Cœur 3', 'Ligne 23'),
  ('Télécentre', 'Ligne 23'),
  ('Point E', 'Ligne 23'),
  ('Sacré Cœur 3', 'Ligne 23'),
  ('Route de l’Aéroport', 'Ligne 23'),
  ('Lycée Lamine Gueye', 'Ligne 23'),
  ('Diamaguène Sicap Mbao', 'Ligne 24'),
  ('Cité Lamine Guèye', 'Ligne 24'),
  ('Village Malick', 'Ligne 24'),
  ('Terminus Malick', 'Ligne 24');

INSERT INTO bus (nom_long, ligne)
VALUES
  ('Rufisque', 'Ligne 15A & 15B'),
  ('Palais 1', 'Ligne 15A & 15B'),
  ('Terminus Rufisque', 'Ligne 15A & 15B'),
  ('Mosquée Keuri Kaw', 'Ligne 15A & 15B'),
  ('Sortie Rufisque (Dioukoul)', 'Ligne 15A & 15B'),
  ('Sicap Mbao', 'Ligne 15A & 15B'),
  ('Diamaguène', 'Ligne 15A & 15B'),
  ('Croisement Pikine', 'Ligne 15A & 15B'),
  ('Route de Rufisque', 'Ligne 15A & 15B'),
  ('SCOA', 'Ligne 15A & 15B'),
  ('SONACOS', 'Ligne 15A & 15B'),
  ('Bld de l’Arsenal', 'Ligne 15A & 15B'),
  ('Esso Port', 'Ligne 15A & 15B'),
  ('Place de l’Indépendance', 'Ligne 15A & 15B'),
  ('Avenue Léopold Sédar Senghor', 'Ligne 15A & 15B'),
  ('Avenue Nelson Mandela', 'Ligne 15A & 15B'),
  ('Palais 1', 'Ligne 15A & 15B');

INSERT INTO bus (nom_long, ligne)
VALUES
('Malika', 'Ligne 16A'),
('Palais 1', 'Ligne 16A'),
('Terminus Malika', 'Ligne 16A'),
('Yeumbeul', 'Ligne 16A'),
('Tally Diallo', 'Ligne 16A'),
('Icotaf', 'Ligne 16A'),
('Cité Lobatt Fall', 'Ligne 16A'),
('Rond-point Lobatt Fall', 'Ligne 16A'),
('Autoroute', 'Ligne 16A'),
('Colobane', 'Ligne 16A'),
('Rond-point Colobane', 'Ligne 16A'),
('Place Bakou', 'Ligne 16A'),
('Cfao Technologies', 'Ligne 16A'),
('Cyrnos', 'Ligne 16A'),
('Arsenal', 'Ligne 16A'),
('Place de l’Indépendance', 'Ligne 16A'),
('Palais de justice 1', 'Ligne 16A');

INSERT INTO bus (nom_long, ligne)
VALUES
('Malika', 'Ligne 16B'),
('Palais 1', 'Ligne 16B'),
('Terminus Malika', 'Ligne 16B'),
('Station Keur Massar', 'Ligne 16B'),
('Croisement Keur Massar', 'Ligne 16B'),
('LGI Mbao', 'Ligne 16B'),
('Diamaguène', 'Ligne 16B'),
('Thiaroye', 'Ligne 16B'),
('Sips', 'Ligne 16B'),
('Sotiba (seras)', 'Ligne 16B'),
('Yarakh', 'Ligne 16B'),
('Capa Virmaud', 'Ligne 16B'),
('Place Bakou', 'Ligne 16B'),
('(Scoa)', 'Ligne 16B'),
('Police Bel Air', 'Ligne 16B'),
('Bel Air', 'Ligne 16B'),
('GMD', 'Ligne 16B'),
('Sofrigal (môle 8)', 'Ligne 16B'),
('Cyrnos (sur le pont)', 'Ligne 16B'),
('Caserne Sapeurs Pompiers', 'Ligne 16B'),
('Avenue Lamine Guèye (Sandaga)', 'Ligne 16B'),
('Avenue André Peytavin', 'Ligne 16B'),
('Avenue Jean Jaurès', 'Ligne 16B'),
('Boulevard de la République', 'Ligne 16B'),
('Avenue Léopold Sédar Senghor (Roume)', 'Ligne 16B'),
('Hôpital Principal', 'Ligne 16B'),
('Assemblée Nationale', 'Ligne 16B'),
('Hôpital Le Dantec', 'Ligne 16B'),
('Palais 1', 'Ligne 16B');

INSERT INTO bus (nom_long, ligne)
VALUES
('Bayakh', 'Ligne 208'),
('Rufisque', 'Ligne 208'),
('Gorom 01', 'Ligne 208'),
('Gororm 02', 'Ligne 208'),
('Bambilor', 'Ligne 208'),
('Noflaye', 'Ligne 208'),
('Sangalkam', 'Ligne 208'),
('Keur Ndiaye Lo', 'Ligne 208'),
('Rufisque', 'Ligne 208');

INSERT INTO bus (nom_long, ligne)
VALUES
('Rufisque', 'Ligne 213'),
('Dieuppeul', 'Ligne 213'),
('Gare de Rufisque', 'Ligne 213'),
('HLM SIPRES', 'Ligne 213'),
('ZAC Mbao', 'Ligne 213'),
('Grand Mbao', 'Ligne 213'),
('Stade Mbao', 'Ligne 213'),
('Petit Mbao', 'Ligne 213'),
('Croisement Petit Mbao', 'Ligne 213'),
('RN1', 'Ligne 213'),
('poste Thiaroye', 'Ligne 213'),
('péage', 'Ligne 213'),
('sortie Cambérène', 'Ligne 213'),
('Patte d’Oie', 'Ligne 213'),
('Marche Grand Yoff', 'Ligne 213'),
('Police Grand Yoff', 'Ligne 213'),
('Rond-Point Liberté 6', 'Ligne 213'),
('Terminus Dieuppeul', 'Ligne 213');

INSERT INTO bus (nom_long, ligne)
VALUES
('Thiaroye', 'Ligne 217'),
('Ouakam', 'Ligne 217'),
('Dépôt Thiaroye', 'Ligne 217'),
('police Thiaroye', 'Ligne 217'),
('Route des Niayes', 'Ligne 217'),
('Pikine', 'Ligne 217'),
('Canada Golf Fadia', 'Ligne 217'),
('Case bi', 'Ligne 217'),
('Croisement 22', 'Ligne 217'),
('Eglise', 'Ligne 217'),
('Terminus parcelles Assainies', 'Ligne 217'),
('Dior Centre Bceao', 'Ligne 217'),
('Route cimetière Yoff', 'Ligne 217'),
('Route de L’Aéroport', 'Ligne 217'),
('Ngor– route des Almadies', 'Ligne 217'),
('Mamelles', 'Ligne 217'),
('Marché Ouakam', 'Ligne 217'),
('Terminus Ouakam', 'Ligne 217');

INSERT INTO bus (nom_long, ligne)
VALUES
('Thiaroye', 'Ligne 218'),
('Aéroport LSS', 'Ligne 218'),
('Dépôt Thiaroye', 'Ligne 218'),
('Route Nationale N° 1', 'Ligne 218'),
('Pikine', 'Ligne 218'),
('patte d’oies', 'Ligne 218'),
('Foire', 'Ligne 218'),
('VDN', 'Ligne 218'),
('Sipres', 'Ligne 218'),
('ancienne piste', 'Ligne 218'),
('Ouakam', 'Ligne 218'),
('marché Ouakam', 'Ligne 218'),
('terminus Ouakam', 'Ligne 218'),
('route des mamelles', 'Ligne 218'),
('route des Almadies', 'Ligne 218'),
('Ngor', 'Ligne 218'),
('Terminus aéroport LSS', 'Ligne 218');

INSERT INTO bus (nom_long, ligne)
VALUES
('Daroukhane', 'Ligne 219'),
('Ouakam', 'Ligne 219'),
('Daroukhane', 'Ligne 219'),
('marché Ndiarème', 'Ligne 219'),
('deux voies Pikine Notaire', 'Ligne 219'),
('Terminus Guédiawaye', 'Ligne 219'),
('Stade Amadou Barry', 'Ligne 219'),
('Marché Sham', 'Ligne 219'),
('Marché Jeudi corniche', 'Ligne 219'),
('Croisement Béthio', 'Ligne 219'),
('Fadia', 'Ligne 219'),
('Case bi', 'Ligne 219'),
('Pont Sénégal 92', 'Ligne 219'),
('Collège Hyacinthe Thiandoum', 'Ligne 219'),
('Deux voies liberté 6', 'Ligne 219'),
('Ancienne Piste', 'Ligne 219'),
('Hôpital militaire de Ouakam', 'Ligne 219'),
('Comico', 'Ligne 219'),
('Cité Asecna', 'Ligne 219'),
('Cité Assemblée', 'Ligne 219'),
('Terminus Ouakam', 'Ligne 219');

INSERT INTO bus (nom_long, ligne)
VALUES
('Rufisque', 'Ligne 220'),
('Guédiawaye', 'Ligne 220'),
('Terminus Rufisque', 'Ligne 220'),
('Djoutiba', 'Ligne 220'),
('HLM Rufisque', 'Ligne 220'),
('SIPRES', 'Ligne 220'),
('SEDIMA', 'Ligne 220'),
('Lycée Jaxaay-2 voies', 'Ligne 220'),
('Jaxaay', 'Ligne 220'),
('Station Keur Massar', 'Ligne 220'),
('Terminus Malika', 'Ligne 220'),
('Malika Plage', 'Ligne 220'),
('Sortie Autoroute', 'Ligne 220'),
('Serigne Assane', 'Ligne 220'),
('Lycée Limamoulaye', 'Ligne 220'),
('Terminus Guédiawaye', 'Ligne 220');

INSERT INTO bus (nom_long, ligne)
VALUES
('Gadaye', 'Ligne 221'),
('Almadies', 'Ligne 221'),
('Cité Gadaye (Filaos)', 'Ligne 221'),
('Corniche Daroukhane', 'Ligne 221'),
('Hamo 6', 'Ligne 221'),
('Arrêt Dial Mbaye', 'Ligne 221'),
('PAI', 'Ligne 221'),
('Dalal Diam', 'Ligne 221'),
('Case', 'Ligne 221'),
('Police PA', 'Ligne 221'),
('Pont Sénégal emergent', 'Ligne 221'),
('Route de l’aéroport', 'Ligne 221'),
('Yoff Tonghor', 'Ligne 221'),
('Cite Asecna', 'Ligne 221'),
('Rond-point Ngor', 'Ligne 221'),
('Ngor village', 'Ligne 221'),
('Almadies', 'Ligne 221');

INSERT INTO bus (nom_long, ligne)
VALUES
('Terminus Keur Massar', 'Ligne 227'),
('Terminus Parcelles', 'Ligne 227'),
('Terminus Keur Massar', 'Ligne 227'),
('Station Keur Massar', 'Ligne 227'),
('Hôpital Keur Massar', 'Ligne 227'),
('Keur Massar', 'Ligne 227'),
('Terminus Malika', 'Ligne 227'),
('Malika plage', 'Ligne 227'),
('Sortie autoroute', 'Ligne 227'),
('Stade amadou Barry', 'Ligne 227'),
('CES Canada', 'Ligne 227'),
('Pharmacie Golf', 'Ligne 227'),
('Fadia', 'Ligne 227'),
('Case bi', 'Ligne 227'),
('Croisement 22', 'Ligne 227'),
('Eglise PA', 'Ligne 227'),
('Terminus Parcelles', 'Ligne 227');

INSERT INTO bus (nom_long, ligne)
VALUES
('Terminus Rufisque', 'Ligne 228'),
('Yenne', 'Ligne 228'),
('Terminus Rufisque', 'Ligne 228'),
('ville de Rufisque', 'Ligne 228'),
('Bargny', 'Ligne 228'),
('Diamniadio Yenne', 'Ligne 228');

INSERT INTO bus (nom_long, ligne)
VALUES
('Baux Maraichers', 'Ligne 232'),
('Aéroport LSS', 'Ligne 232'),
('Baux Maraichers', 'Ligne 232'),
('Yarakh', 'Ligne 232'),
('Cafétéria', 'Ligne 232'),
('Hann Maristes', 'Ligne 232'),
('Cours Sainte Marie de Hann', 'Ligne 232'),
('Usine des eaux', 'Ligne 232'),
('Front de terre', 'Ligne 232'),
('Khar Yalla', 'Ligne 232'),
('Rond-Point Liberté 6', 'Ligne 232'),
('deux voies vers Camp Leclerc', 'Ligne 232'),
('Foire', 'Ligne 232'),
('Itinéraire ligne 8', 'Ligne 232'),
('Terminus Aéroport LSS', 'Ligne 232');

INSERT INTO bus (nom_long, ligne)
VALUES
('Baux Maraichers', 'Ligne 233'),
('Palais 1', 'Ligne 233'),
('Baux Maraichers', 'Ligne 233'),
('RN1', 'Ligne 233'),
('Croisement Cambérène', 'Ligne 233'),
('Mariste', 'Ligne 233'),
('Castors', 'Ligne 233'),
('Itinéraire ligne13', 'Ligne 233'),
('Rond-point maison PS', 'Ligne 233'),
('Hampathé Ba', 'Ligne 233'),
('Cité Claudel', 'Ligne 233'),
('Immeuble Dieze', 'Ligne 233'),
('Rue 6', 'Ligne 233'),
('Malick Sy', 'Ligne 233'),
('Poste Médine', 'Ligne 233'),
('Ave Blaise Diagne', 'Ligne 233'),
('Avenue Peytavin', 'Ligne 233'),
('Ponty', 'Ligne 233'),
('Place de l’Indépendance', 'Ligne 233'),
('Hôpital Principal', 'Ligne 233'),
('Hôpital Le Dantec', 'Ligne 233'),
('Palais 1', 'Ligne 233');

INSERT INTO bus (nom_long, ligne)
VALUES
('Jaxaay', 'Ligne 234'),
('Leclerc', 'Ligne 234'),
('Mosquée Niakoul Rab', 'Ligne 234'),
('Ecole Panthéon', 'Ligne 234'),
('2 voies Jaxaay', 'Ligne 234'),
('Station Keur Massar', 'Ligne 234'),
('Croisement Keur Massar', 'Ligne 234'),
('Fass Mbao', 'Ligne 234'),
('Diamagueune', 'Ligne 234'),
('Poste Thiaroye', 'Ligne 234'),
('Autoroute', 'Ligne 234'),
('Péage', 'Ligne 234'),
('AIBD', 'Ligne 234');

INSERT INTO bus (nom_long, ligne)
VALUES

('Terminus Ouakam', 'Ligne 401'),
('Mamelles', 'Ligne 401'),
('Croisement Almadies', 'Ligne 401'),
('Ngor', 'Ligne 401'),
('Yoff', 'Ligne 401'),
('Rte de l’Aéroport', 'Ligne 401'),
('Foire', 'Ligne 401'),
('VDN', 'Ligne 401'),
('Direction Générale DDD', 'Ligne 401'),
('Rond-Point JVC', 'Ligne 401'),
('Rond-Point Liberté 6', 'Ligne 401'),
('Itinéraire 213', 'Ligne 401'),
('Police Grand Yoff', 'Ligne 401'),
('Pharmacie Patte d’Oie', 'Ligne 401'),
('Terminus Sphère', 'Ligne 401');

INSERT INTO bus (nom_long, ligne)
VALUES
('Terminus Ouakam', 'Ligne 402'),
('Marché Ouakam', 'Ligne 402'),
('Carrefour Yarakh', 'Ligne 402'),
('Poste Mamelles', 'Ligne 402'),
('Almadies', 'Ligne 402'),
('Phare des Mamelles', 'Ligne 402'),
('corniche Ouest', 'Ligne 402'),
('Yoff APECSY', 'Ligne 402'),
('Cité Gadaye', 'Ligne 402');

INSERT INTO bus (nom_long, ligne)
VALUES
('Liberté 5', 'Ligne 13'),
('Palais 2', 'Ligne 13'),
('Terminus Dieuppeul', 'Ligne 13'),
('Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)', 'Ligne 13'),
('Station Castors', 'Ligne 13'),
('Cité Port', 'Ligne 13'),
('Lycée Kennedy', 'Ligne 13'),
('Bld Général De Gaule', 'Ligne 13'),
('Allées Papa Guèye Fall', 'Ligne 13'),
('Avenue Faidherbe', 'Ligne 13'),
('Esso Port', 'Ligne 13'),
('Place de l’Indépendance', 'Ligne 13'),
('Avenue Léopold Sédar Senghor', 'Ligne 13'),
('Avenue Nelson Mandela', 'Ligne 13'),
('Palais 2', 'Ligne 13');

INSERT INTO bus (nom_long, ligne)
VALUES
('Daroukhane', 'Ligne 2'),
('Corniche-Hamo', 'Ligne 2'),
('Terminus Guédiawaye', 'Ligne 2'),
('Marché Sahm', 'Ligne 2'),
('Ecole Canada', 'Ligne 2'),
('Route des Niayes', 'Ligne 2'),
('Tally Boumack (route de l’Ouest)', 'Ligne 2'),
('Route Nationale n° 1', 'Ligne 2'),
('Autoroute', 'Ligne 2'),
('Cité des Eaux', 'Ligne 2'),
('Avenue Bourguiba', 'Ligne 2'),
('Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée)', 'Ligne 2'),
('Bld Général De Gaule', 'Ligne 2'),
('Rue 25', 'Ligne 2'),
('Avenue Blaise Diagne', 'Ligne 2'),
('Avenue Jean Jaurès', 'Ligne 2'),
('Avenue Georges Pompidou', 'Ligne 2'),
('Place de l’Indépendance', 'Ligne 2'),
('Esso Port', 'Ligne 2'),
('Place Leclerc', 'Ligne 2');

INSERT INTO bus (nom_long, ligne)
VALUES
('Cambéréne 2', 'Ligne 6'),
('Cambéréne village', 'Ligne 6'),
('Case', 'Ligne 6'),
('Route des Niayes', 'Ligne 6'),
('Police des Parcelles Assainies', 'Ligne 6'),
('Marché Grand-Médine', 'Ligne 6'),
('Cité Keur Damel', 'Ligne 6'),
('VDN Sipres', 'Ligne 6'),
('Camp Pénal', 'Ligne 6'),
('Derklé', 'Ligne 6'),
('Liberté 5', 'Ligne 6'),
('Allées Khalifa Ababacar Sy', 'Ligne 6'),
('Jet d’Eau', 'Ligne 6'),
('Niary Tally', 'Ligne 6'),
('Enam', 'Ligne 6'),
('Bld Général De Gaule', 'Ligne 6'),
('Allées Papa Guèye Fall', 'Ligne 6'),
('Avenue Faidherbe', 'Ligne 6'),
('Avenue Lamine Guèye', 'Ligne 6'),
('Avenue André Peytavin', 'Ligne 6'),
('Avenue Jean Jaurès', 'Ligne 6'),
('Bld de la République', 'Ligne 6'),
('Avenue Nelson Mandela', 'Ligne 6'),
('Palais 2', 'Ligne 6');

INSERT INTO bus (nom_long, ligne)
VALUES
('Guédiawaye', 'Ligne 5'),
('Route de la Corniche', 'Ligne 5'),
('Cité des Enseignants', 'Ligne 5'),
('Maison du PAI', 'Ligne 5'),
('Cité Hlm', 'Ligne 5'),
('Golf', 'Ligne 5'),
('Route des Niayes', 'Ligne 5'),
('Police de Parcelles Assainies', 'Ligne 5'),
('Pont du Stade Léopold Sédar Senghor (Echangeur)', 'Ligne 5'),
('Patte d’Oie', 'Ligne 5'),
('Autoroute', 'Ligne 5'),
('Passage Cyrnos', 'Ligne 5'),
('Avenue Lamine Guèye', 'Ligne 5'),
('Avenue André Peytavin', 'Ligne 5'),
('Avenue Jean Jaurès', 'Ligne 5'),
('Bld de la République', 'Ligne 5'),
('Avenue Léopold Sédar Senghor', 'Ligne 5'),
('Avenue Nelson Mandela', 'Ligne 5'),
('Palais de Justice 1', 'Ligne 5');

INSERT INTO bus (nom_long, ligne)
VALUES
('PA', 'Ligne 403'),
('Hôpital Dalal Diam', 'Ligne 403'),
('Itinéraire 227', 'Ligne 403'),
('2 voies Jaxaay', 'Ligne 403'),
('Sedima', 'Ligne 403'),
('Péage', 'Ligne 403'),
('AIBD', 'Ligne 403'),
('Parcelles vers Sphère', 'Ligne 403');

INSERT INTO bus (nom_long, ligne)
VALUES
('Leclerc', 'Ligne 404A'),
('Ave Albert Sarraut', 'Ligne 404A'),
('Itinéraire ligne 13', 'Ligne 404A'),
('Colobane', 'Ligne 404A'),
('Autoroute à Péage', 'Ligne 404A'),
('Diamniadio', 'Ligne 404A'),
('Itinéraire ligne 228', 'Ligne 404A'),
('Diass', 'Ligne 404A'),
('Croisement Kiréne', 'Ligne 404A'),
('Croisement zone fret', 'Ligne 404A'),
('AIBD', 'Ligne 404A');

INSERT INTO bus (nom_long, ligne)
VALUES
('Leclerc', 'Ligne 404B'),
('Ave Albert Sarraut', 'Ligne 404B'),
('Itinéraire ligne 13', 'Ligne 404B'),
('Colobane', 'Ligne 404B'),
('Autoroute à Péage', 'Ligne 404B'),
('Poste Thiaroye', 'Ligne 404B'),
('itinéraire ligne 402', 'Ligne 404B'),
('AIBD', 'Ligne 404B');

INSERT INTO bus (nom_long, ligne)
VALUES
('Dieuppeul', 'Ligne 405'),
('Jet D’eau', 'Ligne 405'),
('Bourguiba', 'Ligne 405'),
('Allées Seydou Nourou Tall', 'Ligne 405'),
('Canal 4', 'Ligne 405'),
('Autoroute', 'Ligne 405'),
('Péage', 'Ligne 405'),
('AIBD', 'Ligne 405');

INSERT INTO bus (nom_long, ligne)
VALUES
('Guédiawaye', 'Ligne 12'),
('Cité des Enseignants', 'Ligne 12'),
('Maison du PAI', 'Ligne 12'),
('Hlm Guédiawaye', 'Ligne 12'),
('Domaine de Guédiawaye', 'Ligne 12'),
('Lycée Canada', 'Ligne 12'),
('Route des Niayes', 'Ligne 12'),
('Tally Boubess', 'Ligne 12'),
('Marché poissons', 'Ligne 12'),
('Route de Rufisque', 'Ligne 12'),
('Capa', 'Ligne 12'),
('TP Cap Vert', 'Ligne 12'),
('Cité des Eaux', 'Ligne 12'),
('Avenue Bourguiba', 'Ligne 12'),
('Relais Avenue Cheikh Anta Diop (Hôpital Fann)', 'Ligne 12'),
('Avenue Blaise Diagne', 'Ligne 12'),
('Avenue Jean Jaurès', 'Ligne 12'),
('Bld de la République', 'Ligne 12'),
('Avenue Léopold Sédar Senghor', 'Ligne 12'),
('Avenue Nelson Mandela', 'Ligne 12'),
('Palais de Justice', 'Ligne 12');

INSERT INTO bus (nom_long, ligne)
VALUES
('Scat Urbam', 'Ligne 121'),
('Mairie grand Yoff', 'Ligne 121'),
('Cité Cse', 'Ligne 121'),
('Les deux voies de Sipres', 'Ligne 121'),
('Les deux voies de Liberté 6', 'Ligne 121'),
('Collège Sacré Cœur', 'Ligne 121'),
('Sicap rue 10', 'Ligne 121'),
('Lycée Blaise Diagne', 'Ligne 121'),
('Place ONU', 'Ligne 121'),
('Canal 4', 'Ligne 121'),
('HLM Fass', 'Ligne 121'),
('Travaux communaux', 'Ligne 121'),
('Rue 22 prolongée', 'Ligne 121'),
('Rts', 'Ligne 121'),
('Allées Papa Guèye Fall', 'Ligne 121'),
('Avenue Faidherbe', 'Ligne 121'),
('Place de l’indépendance', 'Ligne 121'),
('Albert Sarraut', 'Ligne 121'),
('Terminus Leclerc', 'Ligne 121');

