

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus HLM Grand Yoff (Face Autoroute)', 'Ligne 1', 'AFTU'),
('Scat Urbam', 'Ligne 1', 'AFTU'),
('Liberté 6', 'Ligne 1', 'AFTU'),
('Derklé', 'Ligne 1', 'AFTU'),
('Liberté 4', 'Ligne 1', 'AFTU'),
('Rond Point Jet d''eau', 'Ligne 1', 'AFTU'),
('Bourguiba', 'Ligne 1', 'AFTU'),
('Grand Dakar', 'Ligne 1', 'AFTU'),
('Fass Médina', 'Ligne 1', 'AFTU'),
('Sham', 'Ligne 1', 'AFTU'),
('Avenue Blaise Diagne', 'Ligne 1', 'AFTU'),
('Terminus Lat Dior', 'Ligne 1', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Daroukhane', 'Ligne 2', 'DDD'),
('Corniche-Hamo', 'Ligne 2', 'DDD'),
('Terminus Guédiawaye', 'Ligne 2', 'DDD'),
('Marché Sahm', 'Ligne 2', 'DDD'),
('Ecole Canada', 'Ligne 2', 'DDD'),
('Route des Niayes', 'Ligne 2', 'DDD'),
('Tally Boumack (route de l’Ouest)', 'Ligne 2', 'DDD'),
('Route Nationale n° 1', 'Ligne 2', 'DDD'),
('Autoroute', 'Ligne 2', 'DDD'),
('Cité des Eaux', 'Ligne 2', 'DDD'),
('Avenue Bourguiba', 'Ligne 2', 'DDD'),
('Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée)', 'Ligne 2', 'DDD'),
('Bld Général De Gaule', 'Ligne 2', 'DDD'),
('Rue 25', 'Ligne 2', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 2', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 2', 'DDD'),
('Avenue Georges Pompidou', 'Ligne 2', 'DDD'),
('Place de l’Indépendance', 'Ligne 2', 'DDD'),
('Esso Port', 'Ligne 2', 'DDD'),
('Place Leclerc', 'Ligne 2', 'DDD');


INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Yoff Village', 'Ligne 3', 'AFTU'),
('Aéroport LSS', 'Ligne 3', 'AFTU'),
('Route de Ngor', 'Ligne 3', 'AFTU'),
('Almadies', 'Ligne 3', 'AFTU'),
('Les Mamelles (Monument Renaissance)', 'Ligne 3', 'AFTU'),
('Ouakam', 'Ligne 3', 'AFTU'),
('Hôpital Fann', 'Ligne 3', 'AFTU'),
('UCAD/ENDSS', 'Ligne 3', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 3', 'AFTU'),
('Avenue Blaise Diagne', 'Ligne 3', 'AFTU'),
('Terminus Pétersen', 'Ligne 3', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Dieuppeul', 'Ligne 4', 'DDD'),
('Cité Derklé', 'Ligne 4', 'DDD'),
('Khar Yalla', 'Ligne 4', 'DDD'),
('Cité Marine', 'Ligne 4', 'DDD'),
('CEG Dieuppeul 3', 'Ligne 4', 'DDD'),
('Camp Sapeurs-Pompiers', 'Ligne 4', 'DDD'),
('Cité Sacré Cœur', 'Ligne 4', 'DDD'),
('Collège Sacré Cœur', 'Ligne 4', 'DDD'),
('Sicap Karack', 'Ligne 4', 'DDD'),
('Avenue Bourguiba', 'Ligne 4', 'DDD'),
('Dial Diop ex rue 10', 'Ligne 4', 'DDD'),
('Point E', 'Ligne 4', 'DDD'),
('HLM Fass', 'Ligne 4', 'DDD'),
('Canal Gueule Tapée', 'Ligne 4', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 4', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 4', 'DDD'),
('Boulevard de la République', 'Ligne 4', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 4', 'DDD'),
('Allées Canard-Esso Port Embarcadère', 'Ligne 4', 'DDD'),
('Terminus Leclerc', 'Ligne 4', 'DDD');


INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Guédiawaye', 'Ligne 5', 'DDD'),
('Route de la Corniche', 'Ligne 5', 'DDD'),
('Cité des Enseignants', 'Ligne 5', 'DDD'),
('Maison du PAI', 'Ligne 5', 'DDD'),
('Cité Hlm', 'Ligne 5', 'DDD'),
('Golf', 'Ligne 5', 'DDD'),
('Route des Niayes', 'Ligne 5', 'DDD'),
('Police de Parcelles Assainies', 'Ligne 5', 'DDD'),
('Pont du Stade Léopold Sédar Senghor (Echangeur)', 'Ligne 5', 'DDD'),
('Patte d’Oie', 'Ligne 5', 'DDD'),
('Autoroute', 'Ligne 5', 'DDD'),
('Passage Cyrnos', 'Ligne 5', 'DDD'),
('Avenue Lamine Guèye', 'Ligne 5', 'DDD'),
('Avenue André Peytavin', 'Ligne 5', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 5', 'DDD'),
('Bld de la République', 'Ligne 5', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 5', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 5', 'DDD'),
('Palais de Justice 1', 'Ligne 5', 'DDD');


INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Guédiawaye', 'Ligne 24', 'AFTU'),
('Sapeur Pompier Guédiawaye', 'Ligne 24', 'AFTU'),
('Sonatel Guédiawaye', 'Ligne 24', 'AFTU'),
('Marché Peund Lansar', 'Ligne 24', 'AFTU'),
('Ecole Lansar (CEM Thiaroye Djiaddah Kao)', 'Ligne 24', 'AFTU'),
('Tally Bou Bess', 'Ligne 24', 'AFTU'),
('Bountou Pikine', 'Ligne 24', 'AFTU'),
('Autoroute', 'Ligne 24', 'AFTU'),
('Cité des Eaux', 'Ligne 24', 'AFTU'),
('Station Castor', 'Ligne 24', 'AFTU'),
('Jet d''eau', 'Ligne 24', 'AFTU'),
('Bourguiba', 'Ligne 24', 'AFTU'),
('Ecole Normale / Ecole Police', 'Ligne 24', 'AFTU'),
('Hôpital Fann', 'Ligne 24', 'AFTU'),
('Terminus Cheikh Anta Diop UCAD', 'Ligne 24', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus des Parcelles Assainies', 'Ligne 25', 'AFTU'),
('Foires', 'Ligne 25', 'AFTU'),
('VDN (voie de dégagement Nord)', 'Ligne 25', 'AFTU'),
('Permanence PDS', 'Ligne 25', 'AFTU'),
('Mermoz', 'Ligne 25', 'AFTU'),
('Hôpital Fann', 'Ligne 25', 'AFTU'),
('UCAD/ENDSS', 'Ligne 25', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 25', 'AFTU'),
('Tilène', 'Ligne 25', 'AFTU'),
('Poste Médina', 'Ligne 25', 'AFTU'),
('Crédit Foncier', 'Ligne 25', 'AFTU'),
('Terminus Pétersen', 'Ligne 25', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus des Parcelles Assainies', 'Ligne 26', 'AFTU'),
('Camp Sapeur Pommier Parcelles', 'Ligne 26', 'AFTU'),
('Eglise', 'Ligne 26', 'AFTU'),
('Parcelles Assainies unité 17', 'Ligne 26', 'AFTU'),
('Marché Parcelles Assainies', 'Ligne 26', 'AFTU'),
('Parcelles Assainies unité 03', 'Ligne 26', 'AFTU'),
('Domaine Guédiawaya/Police Golf', 'Ligne 26', 'AFTU'),
('Pont Wakhinane Guediawaye', 'Ligne 26', 'AFTU'),
('PAI', 'Ligne 26', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 26', 'AFTU'),
('Station Tally Boumack', 'Ligne 26', 'AFTU'),
('Station Texaco', 'Ligne 26', 'AFTU'),
('Police Thiaroye', 'Ligne 26', 'AFTU'),
('Lycée Thiaroye', 'Ligne 26', 'AFTU'),
('Rond Point Thiaroye', 'Ligne 26', 'AFTU'),
('Terminus Poste Thiaroye', 'Ligne 26', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Marché Boubess', 'Ligne 27', 'AFTU'),
('Lycée Limamoulaye', 'Ligne 27', 'AFTU'),
('Hôpital Roi Bédouin', 'Ligne 27', 'AFTU'),
('Préfecture Police Guédiawaye', 'Ligne 27', 'AFTU'),
('Sonatel Guédiawaye', 'Ligne 27', 'AFTU'),
('Marché Peund Lansar', 'Ligne 27', 'AFTU'),
('Rue 10', 'Ligne 27', 'AFTU'),
('Cité Lobatt Fall', 'Ligne 27', 'AFTU'),
('Autoroute', 'Ligne 27', 'AFTU'),
('Colobane', 'Ligne 27', 'AFTU'),
('Central Park les Quatre C', 'Ligne 27', 'AFTU'),
('Grande Mosquée de Dakar', 'Ligne 27', 'AFTU'),
('Terminus Pétersen', 'Ligne 27', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Hamo VI', 'Ligne 28', 'AFTU'),
('Arrêt Ndial Mbaye', 'Ligne 28', 'AFTU'),
('Cité des enseignants', 'Ligne 28', 'AFTU'),
('Croisement Béthio', 'Ligne 28', 'AFTU'),
('Golf', 'Ligne 28', 'AFTU'),
('Fadia', 'Ligne 28', 'AFTU'),
('Case Ba', 'Ligne 28', 'AFTU'),
('Croisement Cambèrene', 'Ligne 28', 'AFTU'),
('Autoroute', 'Ligne 28', 'AFTU'),
('Patte D''oie', 'Ligne 28', 'AFTU'),
('Colobane', 'Ligne 28', 'AFTU'),
('RTS', 'Ligne 28', 'AFTU'),
('Terminus Pétersen', 'Ligne 28', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Cité Nations Unis (Cambérène)', 'Ligne 29', 'AFTU'),
('Croisement 22', 'Ligne 29', 'AFTU'),
('Police Parcelle', 'Ligne 29', 'AFTU'),
('Pont Sénégal Emergent', 'Ligne 29', 'AFTU'),
('Liberté 6', 'Ligne 29', 'AFTU'),
('Deux voies de liberté 6', 'Ligne 29', 'AFTU'),
('Avenue Cheikh Anta Diop (UCAD)', 'Ligne 29', 'AFTU'),
('Sham', 'Ligne 29', 'AFTU'),
('Avenue Blaise Diange', 'Ligne 29', 'AFTU'),
('Poste Médina', 'Ligne 29', 'AFTU'),
('Crédit Foncier', 'Ligne 29', 'AFTU'),
('Terminus Pétersen', 'Ligne 29', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Gadaye', 'Ligne 30', 'AFTU'),
('Tounal Baye Laye', 'Ligne 30', 'AFTU'),
('Tounal Serigne Assane', 'Ligne 30', 'AFTU'),
('Stade Ndiarème', 'Ligne 30', 'AFTU'),
('Deux voies Notaires', 'Ligne 30', 'AFTU'),
('Stade Amadou Barry', 'Ligne 30', 'AFTU'),
('Station Canada', 'Ligne 30', 'AFTU'),
('Croisement Béthio', 'Ligne 30', 'AFTU'),
('Cinéma U3', 'Ligne 30', 'AFTU'),
('Case Ba', 'Ligne 30', 'AFTU'),
('Police Parcelle', 'Ligne 30', 'AFTU'),
('Pont Sénégal Emergent', 'Ligne 30', 'AFTU'),
('Grand Yoff', 'Ligne 30', 'AFTU'),
('Camp Pénal', 'Ligne 30', 'AFTU'),
('Liberté 3,4,5,6', 'Ligne 30', 'AFTU'),
('Niary Tally', 'Ligne 30', 'AFTU'),
('Centre de Bob', 'Ligne 30', 'AFTU'),
('Terminus Colobane', 'Ligne 30', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Texaco', 'Ligne 31', 'AFTU'),
('Tally Icotaf', 'Ligne 31', 'AFTU'),
('Cité Lobatt Fall', 'Ligne 31', 'AFTU'),
('Autoroute', 'Ligne 31', 'AFTU'),
('Croisement Cambèrene', 'Ligne 31', 'AFTU'),
('Patte D''oie', 'Ligne 31', 'AFTU'),
('Marché Grand Yoff', 'Ligne 31', 'AFTU'),
('Rond Point Liberté 6', 'Ligne 31', 'AFTU'),
('Sacré coeur', 'Ligne 31', 'AFTU'),
('Deux voies de liberté 6', 'Ligne 31', 'AFTU'),
('Collège Sacré Coeur', 'Ligne 31', 'AFTU'),
('Baobab', 'Ligne 31', 'AFTU'),
('Grand Dakar', 'Ligne 31', 'AFTU'),
('Lycée Kennedy', 'Ligne 31', 'AFTU'),
('Colobane', 'Ligne 31', 'AFTU'),
('Monument', 'Ligne 31', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 31', 'AFTU'),
('Terminus Sham', 'Ligne 31', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Guédiawaye', 'Ligne 32', 'AFTU'),
('Daroukhane', 'Ligne 32', 'AFTU'),
('Corniche Guédiawyae', 'Ligne 32', 'AFTU'),
('Hamo 4,5,6', 'Ligne 32', 'AFTU'),
('Deux Boulangeries Guediawaye', 'Ligne 32', 'AFTU'),
('Marche Jeudi Corniche', 'Ligne 32', 'AFTU'),
('Centre sauvegarde', 'Ligne 32', 'AFTU'),
('CEM Canada', 'Ligne 32', 'AFTU'),
('Station Tally Boumack', 'Ligne 32', 'AFTU'),
('Marché Zing', 'Ligne 32', 'AFTU'),
('Cité Lobatt Fall', 'Ligne 32', 'AFTU'),
('Croisement Cambèrene', 'Ligne 32', 'AFTU'),
('Castor', 'Ligne 32', 'AFTU'),
('Cité des Eaux', 'Ligne 32', 'AFTU'),
('HLM', 'Ligne 32', 'AFTU'),
('Colobane', 'Ligne 32', 'AFTU'),
('Fass Médina', 'Ligne 32', 'AFTU'),
('Terminus Sham', 'Ligne 32', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Daroukhane', 'Ligne 33', 'AFTU'),
('Marché Bou Bess', 'Ligne 33', 'AFTU'),
('Lycée Limamoulaye', 'Ligne 33', 'AFTU'),
('Hôpital Roi Bédouin', 'Ligne 33', 'AFTU'),
('Prèfecture Police Guédiawaye', 'Ligne 33', 'AFTU'),
('Croisement Marché Sham', 'Ligne 33', 'AFTU'),
('CEM Canada', 'Ligne 33', 'AFTU'),
('Centre sauvegarde', 'Ligne 33', 'AFTU'),
('Hôpital Dalal Jamm', 'Ligne 33', 'AFTU'),
('Pharmacie Golf', 'Ligne 33', 'AFTU'),
('Fadia', 'Ligne 33', 'AFTU'),
('Case Ba', 'Ligne 33', 'AFTU'),
('Pont Sénégal Emergent', 'Ligne 33', 'AFTU'),
('Marché Grand Yoff', 'Ligne 33', 'AFTU'),
('Liberté 6', 'Ligne 33', 'AFTU'),
('Castor', 'Ligne 33', 'AFTU'),
('HLM', 'Ligne 33', 'AFTU'),
('Terminus Colobane', 'Ligne 33', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Nord Foire', 'Ligne 34', 'AFTU'),
('Cité SIPRES', 'Ligne 34', 'AFTU'),
('Scat Urbam', 'Ligne 34', 'AFTU'),
('Camp Pénal', 'Ligne 34', 'AFTU'),
('Liberté 6', 'Ligne 34', 'AFTU'),
('Score liberté', 'Ligne 34', 'AFTU'),
('Sicap rue 10', 'Ligne 34', 'AFTU'),
('Zone B', 'Ligne 34', 'AFTU'),
('Lycée Blaise Diagne', 'Ligne 34', 'AFTU'),
('Canal UCAD', 'Ligne 34', 'AFTU'),
('Sham', 'Ligne 34', 'AFTU'),
('Terminus Lat Dior', 'Ligne 34', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Daroukhane', 'Ligne 36', 'AFTU'),
('Arrêt Ndial Mbaye', 'Ligne 36', 'AFTU'),
('Cité des enseignants', 'Ligne 36', 'AFTU'),
('Croisement Béthio', 'Ligne 36', 'AFTU'),
('Hôpital Dalal Jamm', 'Ligne 36', 'AFTU'),
('Pharmacie Golf', 'Ligne 36', 'AFTU'),
('Croisement Dioumadji', 'Ligne 36', 'AFTU'),
('Parcelles Assainies unité 03', 'Ligne 36', 'AFTU'),
('Parcelles Assainies unité 22', 'Ligne 36', 'AFTU'),
('Eglise', 'Ligne 36', 'AFTU'),
('Champ Sapeur Pommier Parcelles', 'Ligne 36', 'AFTU'),
('Yoff Village', 'Ligne 36', 'AFTU'),
('Route de L''Aéroport', 'Ligne 36', 'AFTU'),
('Aéroport LSS', 'Ligne 36', 'AFTU'),
('Virage Ngor', 'Ligne 36', 'AFTU'),
('Terminus Ngor Village', 'Ligne 36', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Pétersen', 'Ligne 37', 'AFTU'),
('SCOA YARAH', 'Ligne 37', 'AFTU'),
('Pont Colobane', 'Ligne 37', 'AFTU'),
('Patte D''oie', 'Ligne 37', 'AFTU'),
('Autoroute', 'Ligne 37', 'AFTU'),
('Croisement Cambèrene', 'Ligne 37', 'AFTU'),
('Bountou Pikine', 'Ligne 37', 'AFTU'),
('Tally Icotaf', 'Ligne 37', 'AFTU'),
('Tally Boumack', 'Ligne 37', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 37', 'AFTU'),
('Stade Amadou Barry', 'Ligne 37', 'AFTU'),
('Prèfecture Police Guédiawaye', 'Ligne 37', 'AFTU'),
('Guédiawaye (Station Touré)', 'Ligne 37', 'AFTU'),
('Guédiawaye (Tournal Serigne Assane)', 'Ligne 37', 'AFTU');
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Cité des Enseignants (Guédiawaye)', 'Ligne 38', 'AFTU'),
('Croisement Béthio', 'Ligne 36', 'AFTU'),
('Domaine Guédiawaya/Police Golf', 'Ligne 38', 'AFTU'),
('Fadia', 'Ligne 38', 'AFTU'),
('Lycée des Parcelles Aissainies', 'Ligne 38', 'AFTU'),
('Rond Point case Ba', 'Ligne 38', 'AFTU'),
('Police Parcelle', 'Ligne 38', 'AFTU'),
('Pont Aliou Sow', 'Ligne 38', 'AFTU'),
('Marché Grand-Yoff', 'Ligne 38', 'AFTU'),
('Hôpital de Grand Yoff (CTO)', 'Ligne 38', 'AFTU'),
('Castor', 'Ligne 38', 'AFTU'),
('Université Bourguiba', 'Ligne 38', 'AFTU'),
('Jet d"eau', 'Ligne 38', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 38', 'AFTU'),
('Centre de Transfusion Sanguine', 'Ligne 38', 'AFTU'),
('Hôpital Fann', 'Ligne 38', 'AFTU'),
('UCAD/ENDSS', 'Ligne 38', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 38', 'AFTU'),
('Terminus Sham', 'Ligne 38', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Diamalaye', 'Ligne 39', 'AFTU'),
('Police Parcelle', 'Ligne 39', 'AFTU'),
('Liberté 6', 'Ligne 39', 'AFTU'),
('Front de Terre', 'Ligne 39', 'AFTU'),
('Castor', 'Ligne 39', 'AFTU'),
('Bourguiba', 'Ligne 39', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 39', 'AFTU'),
('Centre de Transfusion Sanguine', 'Ligne 39', 'AFTU'),
('Hôpital Fann', 'Ligne 39', 'AFTU'),
('UCAD/ENDSS', 'Ligne 39', 'AFTU'),
('Gueule Tapée', 'Ligne 39', 'AFTU'),
('Avenue Blaise Diange', 'Ligne 39', 'AFTU'),
('Agence Sonatel Médina', 'Ligne 39', 'AFTU'),
('Terminus Lat Dior', 'Ligne 39', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Grand Mbao', 'Ligne 40', 'AFTU'),
('Diamaguène', 'Ligne 40', 'AFTU'),
('Agence Sonatel Thiaroye', 'Ligne 40', 'AFTU'),
('Bountou Pikine', 'Ligne 40', 'AFTU'),
('Station Cité Lobat Fall', 'Ligne 40', 'AFTU'),
('Autoroute', 'Ligne 40', 'AFTU'),
('Central Park les Quatre C', 'Ligne 40', 'AFTU'),
('Poste Agence Malick Sy', 'Ligne 40', 'AFTU'),
('Grande Mosquée de Dakar', 'Ligne 40', 'AFTU'),
('Terminus Pétersen', 'Ligne 40', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Guédiawaye Madial', 'Ligne 41', 'AFTU'),
('Guédiawaye(Station Touré)', 'Ligne 41', 'AFTU'),
('Sonatel Guédiawaye', 'Ligne 41', 'AFTU'),
('Marché Peund Lansar', 'Ligne 41', 'AFTU'),
('Station Tally Boumack', 'Ligne 41', 'AFTU'),
('Marché Zing', 'Ligne 41', 'AFTU'),
('Police Pikine', 'Ligne 41', 'AFTU'),
('Bountou Pikine', 'Ligne 41', 'AFTU'),
('Marché Poissons', 'Ligne 41', 'AFTU'),
('Yarakh', 'Ligne 41', 'AFTU'),
('Capa', 'Ligne 41', 'AFTU'),
('Police bel air', 'Ligne 41', 'AFTU'),
('Pont Malick SY', 'Ligne 41', 'AFTU'),
('Pompier', 'Ligne 41', 'AFTU'),
('Grande Mosquée de Dakar', 'Ligne 41', 'AFTU'),
('Gare de Pétersen', 'Ligne 41', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Police Corniche Guédiawaye', 'Ligne 42', 'AFTU'),
('Hamo', 'Ligne 42', 'AFTU'),
('Hamo 4', 'Ligne 42', 'AFTU'),
('Deux Boulangeries Guediawaye', 'Ligne 42', 'AFTU'),
('Cité des enseignants', 'Ligne 42', 'AFTU'),
('Croisement Béthio', 'Ligne 42', 'AFTU'),
('Hôpital Dalal Jamm', 'Ligne 42', 'AFTU'),
('Pharmacie Golf', 'Ligne 42', 'AFTU'),
('Fadia', 'Ligne 42', 'AFTU'),
('Case Ba', 'Ligne 42', 'AFTU'),
('Police Parcelle', 'Ligne 42', 'AFTU'),
('Parcelles Assainies Unité 26', 'Ligne 42', 'AFTU'),
('Foire', 'Ligne 42', 'AFTU'),
('Ancienne Piste', 'Ligne 42', 'AFTU'),
('Terminus Ouakam', 'Ligne 42', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Thiaroye (C.D.Yeumbeul Sud)', 'Ligne 43', 'AFTU'),
('Tally Diallo', 'Ligne 43', 'AFTU'),
('Police Thiaroye', 'Ligne 43', 'AFTU'),
('Station Texaco', 'Ligne 43', 'AFTU'),
('Tally Icotaf', 'Ligne 43', 'AFTU'),
('Stade Alassane Djigo(Sadika)', 'Ligne 43', 'AFTU'),
('Complexe L.S. Senghor', 'Ligne 43', 'AFTU'),
('Bountou Pikine', 'Ligne 43', 'AFTU'),
('Autoroute', 'Ligne 43', 'AFTU'),
('Croisement Cambèrene', 'Ligne 43', 'AFTU'),
('Patte D''oie', 'Ligne 43', 'AFTU'),
('Pont EMG', 'Ligne 43', 'AFTU'),
('HLM', 'Ligne 43', 'AFTU'),
('Mermoz', 'Ligne 43', 'AFTU'),
('Bourguiba', 'Ligne 43', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 43', 'AFTU'),
('Ouakam', 'Ligne 43', 'AFTU'),
('Terminus Ouakam Cité Avion', 'Ligne 43', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Ouakam Bayé', 'Ligne 44', 'AFTU'),
('ENEA Aouakam', 'Ligne 44', 'AFTU'),
('Ecole des Officiers de la Gendarmerie', 'Ligne 44', 'AFTU'),
('Rond Point Ecole Normale', 'Ligne 44', 'AFTU'),
('VDN ( voie de dégagement Nord)', 'Ligne 44', 'AFTU'),
('Foires', 'Ligne 44', 'AFTU'),
('Pont Sénégal Emergent', 'Ligne 44', 'AFTU'),
('Patte D''oie', 'Ligne 44', 'AFTU'),
('Autoroute', 'Ligne 44', 'AFTU'),
('Bountou Pikine', 'Ligne 44', 'AFTU'),
('Cap des buches', 'Ligne 44', 'AFTU'),
('Poste Thiaroye', 'Ligne 44', 'AFTU'),
('Diamaguène', 'Ligne 44', 'AFTU'),
('Petit Mbao', 'Ligne 44', 'AFTU'),
('Sicap Mbao', 'Ligne 44', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 44', 'AFTU'),
('Terminus Grand Mbao Extention', 'Ligne 44', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Guédiawaye Notaire', 'Ligne 46', 'AFTU'),
('Sonatel Guédiawaye', 'Ligne 46', 'AFTU'),
('Pikine Rue 10', 'Ligne 46', 'AFTU'),
('Cité Lobatt Fall', 'Ligne 46', 'AFTU'),
('Autoroute', 'Ligne 46', 'AFTU'),
('Patte D''oie', 'Ligne 46', 'AFTU'),
('Grand Yoff', 'Ligne 46', 'AFTU'),
('Collège Hyacinthe Thiandoum', 'Ligne 46', 'AFTU'),
('Rond Point Liberté 6', 'Ligne 46', 'AFTU'),
('Stade Demba Diop', 'Ligne 46', 'AFTU'),
('Bourguiba', 'Ligne 46', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 46', 'AFTU'),
('UCAD/ENDSS', 'Ligne 46', 'AFTU'),
('Tilène', 'Ligne 46', 'AFTU'),
('Sadanga-Ponty', 'Ligne 46', 'AFTU'),
('Gare Lat Dior', 'Ligne 46', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Almadies', 'Ligne 47', 'AFTU'),
('Yoff', 'Ligne 47', 'AFTU'),
('Aéroport LSS', 'Ligne 47', 'AFTU'),
('Route de L''Aéroport', 'Ligne 47', 'AFTU'),
('Rond Point Sénégal Emergent', 'Ligne 47', 'AFTU'),
('Collège Hyacinthe Thiandoum', 'Ligne 47', 'AFTU'),
('Rond Point Liberté 6', 'Ligne 47', 'AFTU'),
('Front de Terre', 'Ligne 47', 'AFTU'),
('Castor', 'Ligne 47', 'AFTU'),
('Avenue bourguiba', 'Ligne 47', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 47', 'AFTU'),
('Hôpital Fann', 'Ligne 47', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 47', 'AFTU'),
('Tilène', 'Ligne 47', 'AFTU'),
('Centre Douta SECK', 'Ligne 47', 'AFTU'),
('Centre Douta SECK', 'Ligne 47', 'AFTU'),
('Sandaga', 'Ligne 47', 'AFTU'),
('Gare Lat Dior', 'Ligne 47', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Cité Serigne Mansour (Rufisque)', 'Ligne 48', 'AFTU'),
('Sonadis Rufisque', 'Ligne 48', 'AFTU'),
('Plateau(Rufisque)', 'Ligne 48', 'AFTU'),
('Rufsa', 'Ligne 48', 'AFTU'),
('Mbao', 'Ligne 48', 'AFTU'),
('Petit Mbao', 'Ligne 48', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 48', 'AFTU'),
('Diamaguène', 'Ligne 48', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 48', 'AFTU'),
('Poste Thiaroye', 'Ligne 48', 'AFTU'),
('Bountou Pikine', 'Ligne 48', 'AFTU'),
('Croisement Cambèrene', 'Ligne 48', 'AFTU'),
('Autoroute', 'Ligne 48', 'AFTU'),
('Colobane', 'Ligne 48', 'AFTU'),
('Pompier', 'Ligne 48', 'AFTU'),
('Poste Agence Malick Sy', 'Ligne 48', 'AFTU'),
('Gare Lat Dior', 'Ligne 48', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Gadaye', 'Ligne 49', 'AFTU'),
('Tournal Baye Laye', 'Ligne 49', 'AFTU'),
('Tournal Serigne Assane', 'Ligne 49', 'AFTU'),
('Sapeur Pompier', 'Ligne 49', 'AFTU'),
('Deux voies Notaires', 'Ligne 49', 'AFTU'),
('Arrêt dial Mbaye', 'Ligne 49', 'AFTU'),
('Stade Amadou Barry', 'Ligne 49', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 49', 'AFTU'),
('Station Tally Boumack', 'Ligne 49', 'AFTU'),
('Tally Icotaf', 'Ligne 49', 'AFTU'),
('Bountou Pikine', 'Ligne 49', 'AFTU'),
('Séras de Yarakh', 'Ligne 49', 'AFTU'),
('Route du Front de Terre', 'Ligne 49', 'AFTU'),
('Deux voies de liberté 6', 'Ligne 49', 'AFTU'),
('Boulangerie Jaune', 'Ligne 49', 'AFTU'),
('Gendarmerie Ouakam', 'Ligne 49', 'AFTU'),
('Mamelles', 'Ligne 49', 'AFTU'),
('Terminus Ngor Village', 'Ligne 49', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Malika', 'Ligne 50', 'AFTU'),
('Yeumbeul', 'Ligne 50', 'AFTU'),
('Tally Diallo', 'Ligne 50', 'AFTU'),
('Texaco', 'Ligne 50', 'AFTU'),
('Tally Bou Bess', 'Ligne 50', 'AFTU'),
('Bountou Pikine', 'Ligne 50', 'AFTU'),
('Autoroute', 'Ligne 50', 'AFTU'),
('Croisement Cambèrene', 'Ligne 50', 'AFTU'),
('Patte D''oie', 'Ligne 50', 'AFTU'),
('Autoroute', 'Ligne 50', 'AFTU'),
('Pont EMG', 'Ligne 50', 'AFTU'),
('Colobane', 'Ligne 50', 'AFTU'),
('Pompier', 'Ligne 50', 'AFTU'),
('Central Park les Quatre C', 'Ligne 50', 'AFTU'),
('Grande Mosquée de Dakar', 'Ligne 50', 'AFTU'),
('Gare de Petersen', 'Ligne 50', 'AFTU');
-- Ligne 51
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Plan Jaxaay 1', 'Ligne 51', 'AFTU'),
('Deux voies keur Massar', 'Ligne 51', 'AFTU'),
('Station Keur Massar', 'Ligne 51', 'AFTU'),
('Hôpital keur Massar', 'Ligne 51', 'AFTU'),
('Arrêt Tenba Boune', 'Ligne 51', 'AFTU'),
('Route de BOUNE', 'Ligne 51', 'AFTU'),
('Croisement Yeumbeul', 'Ligne 51', 'AFTU'),
('Djouma Layenne', 'Ligne 51', 'AFTU'),
('Thiaroye (Thierno Ndiaye)', 'Ligne 51', 'AFTU'),
('Thiaroye Tally Diallo', 'Ligne 51', 'AFTU'),
('Police Thiaroye', 'Ligne 51', 'AFTU'),
('Texaco', 'Ligne 51', 'AFTU'),
('Tally Icotaf', 'Ligne 51', 'AFTU'),
('Ecole IACOM de Pikine', 'Ligne 51', 'AFTU'),
('Terminus Gare des beaux Maraîchers', 'Ligne 51', 'AFTU');

-- Ligne 52
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Eglise Bountou Pikine', 'Ligne 52', 'AFTU'),
('Police Pikine', 'Ligne 52', 'AFTU'),
('Marché Zing', 'Ligne 52', 'AFTU'),
('Station Tally Boumack', 'Ligne 52', 'AFTU'),
('Texaco', 'Ligne 52', 'AFTU'),
('Police Thiaroye', 'Ligne 52', 'AFTU'),
('Tally Diallo', 'Ligne 52', 'AFTU'),
('Thiaroye (Thierno Ndiaye)', 'Ligne 52', 'AFTU'),
('Yeumbeul', 'Ligne 52', 'AFTU'),
('Malika', 'Ligne 52', 'AFTU'),
('Mbeubeuss', 'Ligne 52', 'AFTU'),
('Hôpital keur Massar', 'Ligne 52', 'AFTU'),
('Terminus Keur Massar', 'Ligne 52', 'AFTU');

-- Ligne 53
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Lac Rose', 'Ligne 53', 'AFTU'),
('Croisement Niague', 'Ligne 53', 'AFTU'),
('Ndiakhirate', 'Ligne 53', 'AFTU'),
('Route Des Niayes', 'Ligne 53', 'AFTU'),
('Sonadis Rufisque', 'Ligne 53', 'AFTU'),
('Route Nationale 1 (RN1)', 'Ligne 53', 'AFTU'),
('Bargny', 'Ligne 53', 'AFTU'),
('Diamniadio', 'Ligne 53', 'AFTU'),
('Hôpital Des Enfants Diamniadio', 'Ligne 53', 'AFTU'),
('Sébikotane', 'Ligne 53', 'AFTU');

-- Ligne 54
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Keur Massar', 'Ligne 54', 'AFTU'),
('Route de BOUNE', 'Ligne 54', 'AFTU'),
('Fass MBAO', 'Ligne 54', 'AFTU'),
('Diamaguène', 'Ligne 54', 'AFTU'),
('SIPS', 'Ligne 54', 'AFTU'),
('Sotiba', 'Ligne 54', 'AFTU'),
('Capa', 'Ligne 54', 'AFTU'),
('SCOA YARAH', 'Ligne 54', 'AFTU'),
('Colobane', 'Ligne 54', 'AFTU'),
('Terminus Cheikh Anta Diop UCAD', 'Ligne 54', 'AFTU');

-- Ligne 55
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Gare de Petersen', 'Ligne 55', 'AFTU'),
('Grande Mosquée de Dakar', 'Ligne 55', 'AFTU'),
('Poste Agence Malick Sy', 'Ligne 55', 'AFTU'),
('Yarakh', 'Ligne 55', 'AFTU'),
('SIPS', 'Ligne 55', 'AFTU'),
('Poste Thiaroye', 'Ligne 55', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 55', 'AFTU'),
('Diamaguène', 'Ligne 55', 'AFTU'),
('LGI Mbao', 'Ligne 55', 'AFTU'),
('Croisement Fass Mbao', 'Ligne 55', 'AFTU'),
('Croisement Keur Massar', 'Ligne 55', 'AFTU'),
('Rufsa', 'Ligne 55', 'AFTU'),
('Entrée Rufisque', 'Ligne 55', 'AFTU'),
('Terminus Rufisque', 'Ligne 55', 'AFTU');

-- Ligne 56
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Keur Massar Aladji Pathé', 'Ligne 56', 'AFTU'),
('Croisement Keur Massar', 'Ligne 56', 'AFTU'),
('Diamaguène', 'Ligne 56', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 56', 'AFTU'),
('Poste Thiaroye', 'Ligne 56', 'AFTU'),
('Route Nationale 1(RN1)', 'Ligne 56', 'AFTU'),
('Yarakh', 'Ligne 56', 'AFTU'),
('Cafétaria', 'Ligne 56', 'AFTU'),
('Avenue Elhadji Malick Sy', 'Ligne 56', 'AFTU'),
('Gare de Petersen', 'Ligne 56', 'AFTU');

-- Ligne 57
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Liberté 6', 'Ligne 57', 'AFTU'),
('Grand Yoff', 'Ligne 57', 'AFTU'),
('Collège Hyacinthe Thiandoum', 'Ligne 57', 'AFTU'),
('Patte D''oie', 'Ligne 57', 'AFTU'),
('Autoroute', 'Ligne 57', 'AFTU'),
('Rond Point Cite Lobatt Fall', 'Ligne 57', 'AFTU'),
('Bountou Pikine', 'Ligne 57', 'AFTU'),
('SIPS', 'Ligne 57', 'AFTU'),
('Poste Thiaroye', 'Ligne 57', 'AFTU'),
('Diamaguène', 'Ligne 57', 'AFTU'),
('Sicap Mbao', 'Ligne 57', 'AFTU'),
('Mbao', 'Ligne 57', 'AFTU'),
('Rufsa', 'Ligne 57', 'AFTU'),
('Entrée Rufisque', 'Ligne 57', 'AFTU'),
('Plateau (Rufisque)', 'Ligne 57', 'AFTU'),
('Gouye Mouride (Rufique)', 'Ligne 57', 'AFTU');

-- Ligne 58
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Fass Mbao Rail ba', 'Ligne 58', 'AFTU'),
('Diamaguène', 'Ligne 58', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 58', 'AFTU'),
('Agence Sonatel Thiaroye', 'Ligne 58', 'AFTU'),
('SIPS', 'Ligne 58', 'AFTU'),
('Sotiba', 'Ligne 58', 'AFTU'),
('Capa', 'Ligne 58', 'AFTU'),
('Parc Hann', 'Ligne 58', 'AFTU'),
('Agence le Soleil', 'Ligne 58', 'AFTU'),
('Service des Mines', 'Ligne 58', 'AFTU'),
('Station Castor', 'Ligne 58', 'AFTU'),
('Jet d''eau', 'Ligne 58', 'AFTU'),
('Ecole Normale /Ecole Police', 'Ligne 58', 'AFTU'),
('Hôpital Fann', 'Ligne 58', 'AFTU'),
('UCAD/ENDSS', 'Ligne 58', 'AFTU'),
('Hôpital Abass Ndao', 'Ligne 58', 'AFTU');
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Stade Léopold Senghor', 'Ligne 59', 'AFTU'),
('Police Parcelle', 'Ligne 59', 'AFTU'),
('Croisement 22', 'Ligne 59', 'AFTU'),
('Rond Point case Ba', 'Ligne 59', 'AFTU'),
('Lycée des Parcelles Assainies', 'Ligne 59', 'AFTU'),
('Domaine Guédiawaye/Police Golf', 'Ligne 59', 'AFTU'),
('Ecole Keur Pauline', 'Ligne 59', 'AFTU'),
('Centre sauvegarde', 'Ligne 59', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 59', 'AFTU'),
('Clinique Lansar', 'Ligne 59', 'AFTU'),
('Texaco', 'Ligne 59', 'AFTU'),
('Tally Diallo', 'Ligne 59', 'AFTU'),
('Thiaroye(Thierno Ndiaye)', 'Ligne 59', 'AFTU'),
('Yeumbeul', 'Ligne 59', 'AFTU'),
('Marché Yeumbeul', 'Ligne 59', 'AFTU'),
('MTOA Keur Massar', 'Ligne 59', 'AFTU'),
('Colobane', 'Ligne 60', 'AFTU'),
('Patte D''oie', 'Ligne 60', 'AFTU'),
('Autoroute', 'Ligne 60', 'AFTU'),
('Bountou Pikine', 'Ligne 60', 'AFTU'),
('SIPS', 'Ligne 60', 'AFTU'),
('Poste Thiaroye', 'Ligne 60', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 60', 'AFTU'),
('Diamaguène', 'Ligne 60', 'AFTU'),
('Sicap Mbao', 'Ligne 60', 'AFTU'),
('Mbao', 'Ligne 60', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 60', 'AFTU'),
('Rufsa', 'Ligne 60', 'AFTU'),
('Rufisque', 'Ligne 60', 'AFTU'),
('Terminus Bargny Guedj', 'Ligne 60', 'AFTU'),
('Terminus Keur Massar', 'Ligne 61', 'AFTU'),
('Rond Point Keur Massar', 'Ligne 61', 'AFTU'),
('Parcelles Assainies unité 17', 'Ligne 61', 'AFTU'),
('Patte D''oie', 'Ligne 61', 'AFTU'),
('Rond Point Sénégal Emergent', 'Ligne 61', 'AFTU'),
('Route de L''Aéroport', 'Ligne 61', 'AFTU'),
('Aéroport LSS', 'Ligne 61', 'AFTU'),
('Ngor', 'Ligne 61', 'AFTU'),
('Almadies', 'Ligne 61', 'AFTU'),
('Terminus Mamelles (Pharmacie Mamelles)', 'Ligne 61', 'AFTU'),
('Terminus Gueule Tapée Penc Mi', 'Ligne 62', 'AFTU'),
('Avenue bourguiba', 'Ligne 62', 'AFTU'),
('Jet d''eau', 'Ligne 62', 'AFTU'),
('Castor', 'Ligne 62', 'AFTU'),
('Pont EMG', 'Ligne 62', 'AFTU'),
('Parc Hann', 'Ligne 62', 'AFTU'),
('Agence le Soleil', 'Ligne 62', 'AFTU'),
('Capa', 'Ligne 62', 'AFTU'),
('Yarakh', 'Ligne 62', 'AFTU'),
('SIPS', 'Ligne 62', 'AFTU'),
('Poste Thiaroye', 'Ligne 62', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 62', 'AFTU'),
('Diamaguène', 'Ligne 62', 'AFTU'),
('Mbao', 'Ligne 62', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 62', 'AFTU'),
('Rufsa', 'Ligne 62', 'AFTU'),
('Entrée Rufisque', 'Ligne 62', 'AFTU'),
('Terminus Hôpital Youssou Mbargane (Rufisque)', 'Ligne 62', 'AFTU'),
('Terminus Stade Léopold Senghor', 'Ligne 63', 'AFTU'),
('Cambérène', 'Ligne 63', 'AFTU'),
('Autoroute', 'Ligne 63', 'AFTU'),
('Bountou Pikine', 'Ligne 63', 'AFTU'),
('Poste Thiaroye', 'Ligne 63', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 63', 'AFTU'),
('Diamaguène', 'Ligne 63', 'AFTU'),
('Fass MBAO', 'Ligne 63', 'AFTU'),
('Mbao', 'Ligne 63', 'AFTU'),
('Petit Mbao', 'Ligne 63', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 63', 'AFTU'),
('Rufsa', 'Ligne 63', 'AFTU'),
('Plateau (Rufisque)', 'Ligne 63', 'AFTU'),
('Terminus Castor (Rufisque)', 'Ligne 63', 'AFTU'),
('Terminus Guédiawaye Notaire', 'Ligne 64', 'AFTU'),
('Arrêt Dial Mbaye', 'Ligne 64', 'AFTU'),
('Cité des enseignants', 'Ligne 64', 'AFTU'),
('PAI', 'Ligne 64', 'AFTU'),
('Collège Serigne Cheikh Anta Mbacké (ex canada)', 'Ligne 64', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 64', 'AFTU'),
('Station Tally Boumack', 'Ligne 64', 'AFTU'),
('Marché Zing', 'Ligne 64', 'AFTU'),
('Bountou Pikine', 'Ligne 64', 'AFTU'),
('Poste Thiaroye', 'Ligne 64', 'AFTU'),
('Diamaguène', 'Ligne 64', 'AFTU'),
('Mbao', 'Ligne 64', 'AFTU'),
('Plateau (Rufisque)', 'Ligne 64', 'AFTU'),
('Terminus Thiawlène (Rufisque)', 'Ligne 64', 'AFTU'),
('Terminus Colobane', 'Ligne 65', 'AFTU'),
('SCOA YARAH', 'Ligne 65', 'AFTU'),
('Capa', 'Ligne 65', 'AFTU'),
('Sotiba', 'Ligne 65', 'AFTU'),
('SIPS', 'Ligne 65', 'AFTU'),
('Poste Thiaroye', 'Ligne 65', 'AFTU'),
('Diamaguène', 'Ligne 65', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 65', 'AFTU'),
('Croisement Keur Massar', 'Ligne 65', 'AFTU'),
('keur Massar', 'Ligne 65', 'AFTU'),
('Terminus Jaxaay 2', 'Ligne 65', 'AFTU'),
('Terminus Gorom I', 'Ligne 66', 'AFTU'),
('Gorom II', 'Ligne 66', 'AFTU'),
('Bambilor', 'Ligne 66', 'AFTU'),
('Noflaye', 'Ligne 66', 'AFTU'),
('Sangalkam', 'Ligne 66', 'AFTU'),
('Ndiakhiraate', 'Ligne 66', 'AFTU'),
('Keur Ndiaye Lo', 'Ligne 66', 'AFTU'),
('Rufisque', 'Ligne 66', 'AFTU'),
('Mbao', 'Ligne 66', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 66', 'AFTU'),
('Diamaguène', 'Ligne 66', 'AFTU'),
('Poste Thiaroye', 'Ligne 66', 'AFTU'),
('Bountou Pikine', 'Ligne 66', 'AFTU'),
('Croisement Cambèrene', 'Ligne 66', 'AFTU'),
('Rond Point Sénégal Emergent', 'Ligne 66', 'AFTU'),
('Pont Foire', 'Ligne 66', 'AFTU'),
('Yoff', 'Ligne 66', 'AFTU'),
('Terminus Yoff Frigo', 'Ligne 66', 'AFTU'),
('Terminus Thiawlène (Rufisque)', 'Ligne 67', 'AFTU'),
('Plateau (Rufisque)', 'Ligne 67', 'AFTU'),
('Rufsa', 'Ligne 67', 'AFTU'),
('Mbao', 'Ligne 67', 'AFTU'),
('Petit Mbao', 'Ligne 67', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 67', 'AFTU'),
('Diamaguène', 'Ligne 67', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 67', 'AFTU'),
('Police Thiaroye', 'Ligne 67', 'AFTU'),
('Yarakh', 'Ligne 67', 'AFTU'),
('Cafétaria', 'Ligne 67', 'AFTU'),
('Capa', 'Ligne 67', 'AFTU'),
('Avenue Cheikh Anta Diop (UCAD)', 'Ligne 67', 'AFTU'),
('Ouakam', 'Ligne 67', 'AFTU'),
('Terminus Ouakam Boutique Diallo', 'Ligne 67', 'AFTU'),
('Station Yeumbeul', 'Ligne 68', 'AFTU'),
('Ben Barack', 'Ligne 68', 'AFTU'),
('Malika', 'Ligne 68', 'AFTU'),
('Keur Massar', 'Ligne 68', 'AFTU'),
('Hôpital keur Massar', 'Ligne 68', 'AFTU'),
('Croisement Keur Massar', 'Ligne 68', 'AFTU'),
('Mbao', 'Ligne 68', 'AFTU'),
('Rufsa', 'Ligne 68', 'AFTU'),
('Rufisque', 'Ligne 68', 'AFTU'),
('Plateau (Rufisque)', 'Ligne 68', 'AFTU'),
('Bargny', 'Ligne 68', 'AFTU'),
('Sébikhotane', 'Ligne 68', 'AFTU'),
('Terminus Diamalaye', 'Ligne 69', 'AFTU'),
('Cambérène', 'Ligne 69', 'AFTU'),
('Parcelles Assainies', 'Ligne 69', 'AFTU'),
('Croisement 22', 'Ligne 69', 'AFTU'),
('Croisement Cambèrene', 'Ligne 69', 'AFTU'),
('Cité Lobatt Fall', 'Ligne 69', 'AFTU'),
('Bountou Pikine', 'Ligne 69', 'AFTU'),
('SIPS', 'Ligne 69', 'AFTU'),
('Poste Thiaroye', 'Ligne 69', 'AFTU'),
('Diamaguène', 'Ligne 69', 'AFTU'),
('Croisement Keur Massar', 'Ligne 69', 'AFTU'),
('Station Keur Massar', 'Ligne 69', 'AFTU'),
('Terminus Keur Massar', 'Ligne 69', 'AFTU'),
('Croisement Tivaouane Peulh', 'Ligne 69', 'AFTU'),
('Tivaouane Peulh', 'Ligne 69', 'AFTU'),
('Terminus Tivaouane Peulh', 'Ligne 69', 'AFTU'),
('Tournal Serigne Assane (Guédiawaye)', 'Ligne 70', 'AFTU'),
('Marché Bou Bess', 'Ligne 70', 'AFTU'),
('Lycée Limamoulaye', 'Ligne 70', 'AFTU'),
('Hôpital Roi Baudouin', 'Ligne 70', 'AFTU'),
('Brioche Dorée Guédiawaye', 'Ligne 70', 'AFTU'),
('Station Tally Boumack', 'Ligne 70', 'AFTU'),
('Police Thiaroye', 'Ligne 70', 'AFTU'),
('Lycée Thiaroye', 'Ligne 70', 'AFTU'),
('Poste Thiaroye', 'Ligne 70', 'AFTU'),
('Diamaguène', 'Ligne 70', 'AFTU'),
('LGI Mbao', 'Ligne 70', 'AFTU'),
('Mbao', 'Ligne 70', 'AFTU'),
('Croisement Keur Massar', 'Ligne 70', 'AFTU'),
('Rond Point Keur Massar', 'Ligne 70', 'AFTU'),
('Deux voies Keur Massar', 'Ligne 70', 'AFTU'),
('Cité Pénitentiaire', 'Ligne 70', 'AFTU'),
('Terminus Jaxaay 2', 'Ligne 70', 'AFTU'),
('Terminus Keur Massar (Maison de la Femme)', 'Ligne 71', 'AFTU'),
('Croisement Keur Massar', 'Ligne 71', 'AFTU'),
('Diamaguène', 'Ligne 71', 'AFTU'),
('Poste Thiaroye', 'Ligne 71', 'AFTU'),
('Bountou Pikine', 'Ligne 71', 'AFTU'),
('Autoroute', 'Ligne 71', 'AFTU'),
('Croisement Cambèrene', 'Ligne 71', 'AFTU'),
('Point E', 'Ligne 71', 'AFTU'),
('Relais', 'Ligne 71', 'AFTU'),
('Hôpital Fann', 'Ligne 71', 'AFTU'),
('UCAD/ENDSS', 'Ligne 71', 'AFTU'),
('Canal 4', 'Ligne 71', 'AFTU'),
('Terminus Cité Claudel', 'Ligne 71', 'AFTU'),
('Cité des enseignants (Guédiawaye)', 'Ligne 72', 'AFTU'),
('Hôpital Dalal Jamm', 'Ligne 72', 'AFTU'),
('Centre sauvegarde', 'Ligne 72', 'AFTU'),
('Tribunal Pikine', 'Ligne 72', 'AFTU'),
('Station Tally Boumack', 'Ligne 72', 'AFTU'),
('Police Thiaroye', 'Ligne 72', 'AFTU'),
('Hôpital Thiaroye', 'Ligne 72', 'AFTU'),
('Poste Thiaroye', 'Ligne 72', 'AFTU'),
('Diamaguène', 'Ligne 72', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 72', 'AFTU'),
('Rufsa', 'Ligne 72', 'AFTU'),
('Stade Galandou Diouf', 'Ligne 72', 'AFTU'),
('Croisement Rufisque', 'Ligne 72', 'AFTU'),
('Hôpital Youssou Mbarguane', 'Ligne 72', 'AFTU'),
('Pont Autoroute à péage', 'Ligne 72', 'AFTU'),
('Poste Courant', 'Ligne 72', 'AFTU'),
('Kounoune', 'Ligne 72', 'AFTU'),
('Terminus Kounoune (Cité Cardinal Thiandoum)', 'Ligne 72', 'AFTU'),
('Terminus Poste Thiaroye', 'Ligne 73', 'AFTU'),
('Lycée Thiaroye', 'Ligne 73', 'AFTU'),
('Police Thiaroye', 'Ligne 73', 'AFTU'),
('Thiaroye Tally Diallo', 'Ligne 73', 'AFTU'),
('Thiaroye (Thierno Ndiaye)', 'Ligne 73', 'AFTU'),
('Yeumbeul', 'Ligne 73', 'AFTU'),
('Malika', 'Ligne 73', 'AFTU'),
('Mbeubeuss', 'Ligne 73', 'AFTU'),
('Hôpital Keur Massar', 'Ligne 73', 'AFTU'),
('Station Keur Massar', 'Ligne 73', 'AFTU'),
('Terminus Keur Massar', 'Ligne 73', 'AFTU'),
('Niakoul Rap', 'Ligne 73', 'AFTU'),
('Croisement Niague', 'Ligne 73', 'AFTU'),
('Niague', 'Ligne 73', 'AFTU'),
('Lac Rose', 'Ligne 73', 'AFTU'),
('Terminus Lac Rose', 'Ligne 73', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus cité SOCABEG', 'Ligne 74', 'AFTU'),
('Croisement Tivaouane Peulh', 'Ligne 74', 'AFTU'),
('keur Massar', 'Ligne 74', 'AFTU'),
('Station Keur Massar', 'Ligne 74', 'AFTU'),
('Deux voies keur Massar', 'Ligne 74', 'AFTU'),
('Cité Pénitentiare', 'Ligne 74', 'AFTU'),
('Rufsa', 'Ligne 74', 'AFTU'),
('Rufisque', 'Ligne 74', 'AFTU'),
('Plateau(Rufisque)', 'Ligne 74', 'AFTU'),
('Bargny', 'Ligne 74', 'AFTU'),
('Terminus Bargny Guedj', 'Ligne 74', 'AFTU'),
('Malika (Cité Sonatel)', 'Ligne 75', 'AFTU'),
('Yeumbeul', 'Ligne 75', 'AFTU'),
('Thiaroye (Thierno Ndiaye)', 'Ligne 75', 'AFTU'),
('Thiaroye Tally Diallo', 'Ligne 75', 'AFTU'),
('Hôpital Thiaroye', 'Ligne 75', 'AFTU'),
('Poste Thiaroye', 'Ligne 75', 'AFTU'),
('SIPS', 'Ligne 75', 'AFTU'),
('Bountou Pikine', 'Ligne 75', 'AFTU'),
('Autoroute', 'Ligne 75', 'AFTU'),
('Croisement Cambèrene', 'Ligne 75', 'AFTU'),
('Mariste', 'Ligne 75', 'AFTU'),
('Cité des Eaux', 'Ligne 75', 'AFTU'),
('Castor', 'Ligne 75', 'AFTU'),
('HLM', 'Ligne 75', 'AFTU'),
('Terminus Colobane', 'Ligne 75', 'AFTU'),
('Terminus Sud Foire', 'Ligne 76', 'AFTU'),
('Cité SIPRES', 'Ligne 76', 'AFTU'),
('Marché Grand-Yoff', 'Ligne 76', 'AFTU'),
('Autoroute', 'Ligne 76', 'AFTU'),
('Bountou Pikine', 'Ligne 76', 'AFTU'),
('SIPS', 'Ligne 76', 'AFTU'),
('Agence Sonatel Thiaroye', 'Ligne 76', 'AFTU'),
('Tivaouane Diack Sao', 'Ligne 76', 'AFTU'),
('Diamaguène', 'Ligne 76', 'AFTU'),
('Fass MBAO', 'Ligne 76', 'AFTU'),
('Petit Mbao', 'Ligne 76', 'AFTU'),
('Mbao', 'Ligne 76', 'AFTU'),
('Croisement Keur Massar', 'Ligne 76', 'AFTU'),
('Forêt classée de Mbao', 'Ligne 76', 'AFTU'),
('Rond Point Keur Massar', 'Ligne 76', 'AFTU'),
('Keur Massar', 'Ligne 76', 'AFTU'),
('Terminus Cité Administration Pénitentiaire', 'Ligne 76', 'AFTU'),
('Terminus Rufisque Cité Taco', 'Ligne 77', 'AFTU'),
('Diouti-ba (Daral Rufisque)', 'Ligne 77', 'AFTU'),
('Cap des biches', 'Ligne 77', 'AFTU'),
('Keur Mbaye Fall', 'Ligne 77', 'AFTU'),
('Croisement Keur Massar', 'Ligne 77', 'AFTU'),
('Diamaguène', 'Ligne 77', 'AFTU'),
('Poste Thiaroye', 'Ligne 77', 'AFTU'),
('SIPS', 'Ligne 77', 'AFTU'),
('Bountou Pikine', 'Ligne 77', 'AFTU'),
('Rond Point Cité Lobatt Fall', 'Ligne 77', 'AFTU'),
('Croisement Cambèrene', 'Ligne 77', 'AFTU'),
('Autoroute', 'Ligne 77', 'AFTU'),
('Cité des Eaux', 'Ligne 77', 'AFTU'),
('Senelec Castor', 'Ligne 77', 'AFTU'),
('Castor', 'Ligne 77', 'AFTU'),
('Dieuppeul', 'Ligne 77', 'AFTU'),
('Terminus Liberté 5', 'Ligne 77', 'AFTU'),
('Thiaroye gouy ga', 'Ligne 78', 'AFTU'),
('Tally Diallo', 'Ligne 78', 'AFTU'),
('Station Texaco', 'Ligne 78', 'AFTU'),
('Station Tally Boumack', 'Ligne 78', 'AFTU'),
('Tribunal Pikine Guédiawaye', 'Ligne 78', 'AFTU'),
('PAI', 'Ligne 78', 'AFTU'),
('Police Golf', 'Ligne 78', 'AFTU'),
('Cité Fadia Guentaba', 'Ligne 78', 'AFTU'),
('Rond Point case Ba', 'Ligne 78', 'AFTU'),
('Croisement 22', 'Ligne 78', 'AFTU'),
('Police Parcelles Assainies', 'Ligne 78', 'AFTU'),
('Pont Aliou Sow', 'Ligne 78', 'AFTU'),
('Collège Hyacinthe Thiandoum', 'Ligne 78', 'AFTU'),
('Rond Point Liberté 6', 'Ligne 78', 'AFTU'),
('Terminus Liberté 5', 'Ligne 78', 'AFTU'),
('Cambérène', 'Ligne 79', 'AFTU'),
('Cité Nations Unis (Cambérène)', 'Ligne 79', 'AFTU'),
('Hôpital Dalal Jamm', 'Ligne 79', 'AFTU'),
('Marché Parcelles Assainies', 'Ligne 79', 'AFTU'),
('Patte D''oie', 'Ligne 79', 'AFTU'),
('Préfecture Guédiawaye', 'Ligne 79', 'AFTU'),
('Marché Bou Bess', 'Ligne 79', 'AFTU'),
('Tournal Serigne Assane (Guédiawaye)', 'Ligne 79', 'AFTU'),
('Cité Gadaye', 'Ligne 79', 'AFTU'),
('VDN3', 'Ligne 79', 'AFTU'),
('Malika/Mer', 'Ligne 79', 'AFTU'),
('Hôpital Keur Massar', 'Ligne 79', 'AFTU'),
('Croisement Keur Massar', 'Ligne 79', 'AFTU'),
('Niakoul Rap', 'Ligne 79', 'AFTU'),
('Ndiakhirate', 'Ligne 79', 'AFTU'),
('Sangalkam', 'Ligne 79', 'AFTU'),
('Terminus Diamalaye', 'Ligne 80', 'AFTU'),
('Parcelles Assainies Unité 15 16', 'Ligne 80', 'AFTU'),
('Ecole Fadial', 'Ligne 80', 'AFTU'),
('Caserne Sapeur Pompier', 'Ligne 80', 'AFTU'),
('Croisement 22', 'Ligne 80', 'AFTU'),
('Case Ba', 'Ligne 80', 'AFTU'),
('Cité Nations Unis (Cambérène)', 'Ligne 80', 'AFTU'),
('CEM Cheikh Anta Mbacké (ex Canada)', 'Ligne 80', 'AFTU'),
('Station Tally Boumack', 'Ligne 80', 'AFTU'),
('Police Thiaroye', 'Ligne 80', 'AFTU'),
('Croisement Tally Diallo', 'Ligne 80', 'AFTU'),
('Croisement Yeumbeul', 'Ligne 80', 'AFTU'),
('Ben Barack', 'Ligne 80', 'AFTU'),
('Malika Montagne Mbeubeuss', 'Ligne 80', 'AFTU'),
('Gendarmerie Keur Massar', 'Ligne 80', 'AFTU'),
('Station Keur Massar', 'Ligne 80', 'AFTU'),
('Croisement Tivaouane Peulh', 'Ligne 80', 'AFTU'),
('Poste de Santé Niacoul rap', 'Ligne 80', 'AFTU'),
('Terminus Darou Thioub', 'Ligne 80', 'AFTU'),
('Terminus Gare des beaux Maraîchers', 'Ligne 81', 'AFTU'),
('SIPS', 'Ligne 81', 'AFTU'),
('Agence Sonatel Thiaroye', 'Ligne 81', 'AFTU'),
('Diamaguène', 'Ligne 81', 'AFTU'),
('Sicap Mbao', 'Ligne 81', 'AFTU'),
('Hôpital Sicap Mbao', 'Ligne 81', 'AFTU'),
('Route Nationale 1 (RN1)', 'Ligne 81', 'AFTU'),
('Fass MBAO', 'Ligne 81', 'AFTU'),
('Mbédou Fass', 'Ligne 81', 'AFTU'),
('Tournal Yeumbeul', 'Ligne 81', 'AFTU'),
('Ben Barack', 'Ligne 81', 'AFTU'),
('Malika', 'Ligne 81', 'AFTU'),
('Malika Montagne Mbeubeuss', 'Ligne 81', 'AFTU'),
('Hôpital Keur Massar', 'Ligne 81', 'AFTU'),
('Station Keur Massar', 'Ligne 81', 'AFTU'),
('Terminus Keur Massar', 'Ligne 81', 'AFTU'),
('Cimetière Keur Massar', 'Ligne 81', 'AFTU'),
('Croisement Tivaouane Peulh', 'Ligne 81', 'AFTU'),
('Tivaouane Peulh Darou Salam APIX', 'Ligne 81', 'AFTU'),
('Terminus Cité Taw Feex Tivaouane Peulh', 'Ligne 81', 'AFTU'),
('Cité Comico Yeumbeul', 'Ligne 82', 'AFTU'),
('Boune', 'Ligne 82', 'AFTU'),
('Fass MBAO', 'Ligne 82', 'AFTU'),
('Route Nationale 1 (RN1)', 'Ligne 82', 'AFTU'),
('Diamaguène', 'Ligne 82', 'AFTU'),
('Poste Thiaroye', 'Ligne 82', 'AFTU'),
('SIPS', 'Ligne 82', 'AFTU'),
('Bountou Pikine', 'Ligne 82', 'AFTU'),
('Autoroute', 'Ligne 82', 'AFTU'),
('Patte D''oie', 'Ligne 82', 'AFTU'),
('Colobane', 'Ligne 82', 'AFTU'),
('Médina', 'Ligne 82', 'AFTU'),
('Terminus Gare Lat Dior', 'Ligne 82', 'AFTU'),
('Grand Yoff Bassin', 'Ligne 82', 'AFTU'),
('Hôpital Grand Yoff (Sétéwo)', 'Ligne 82', 'AFTU'),
('Patte D''oie', 'Ligne 82', 'AFTU'),
('Autoroute', 'Ligne 82', 'AFTU'),
('Bountou Pikine', 'Ligne 82', 'AFTU'),
('Poste Thiaroye', 'Ligne 82', 'AFTU'),
('Diamaguène', 'Ligne 82', 'AFTU'),
('Fass MBAO', 'Ligne 82', 'AFTU'),
('Croisement Keur Massar', 'Ligne 82', 'AFTU'),
('Station Keur Massar', 'Ligne 82', 'AFTU'),
('Plan Jaxaay 2', 'Ligne 82', 'AFTU');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Parcelles Assainies', 'Ligne 1', 'DDD'),
('Corniche (U 10-9-15)', 'Ligne 1', 'DDD'),
('Dior', 'Ligne 1', 'DDD'),
('Acapes', 'Ligne 1', 'DDD'),
('Dispensaire Norade', 'Ligne 1', 'DDD'),
('Passage entre U22 et U24', 'Ligne 1', 'DDD'),
('Marché Grand-Médine', 'Ligne 1', 'DDD'),
('VDN', 'Ligne 1', 'DDD'),
('Relais', 'Ligne 1', 'DDD'),
('Avenue Cheikh Anta Diop', 'Ligne 1', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 1', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 1', 'DDD'),
('Avenue André Peytavin', 'Ligne 1', 'DDD'),
('Avenue George Pompidou', 'Ligne 1', 'DDD'),
('Place de l’Indépendance', 'Ligne 1', 'DDD'),
('Allées Canard', 'Ligne 1', 'DDD'),
('Esso Port', 'Ligne 1', 'DDD'),
('Embarcadère', 'Ligne 1', 'DDD'),
('Place Leclerc', 'Ligne 1', 'DDD'),
('Liberté 5', 'Ligne 4', 'DDD'),
('Place Leclerc', 'Ligne 4', 'DDD'),
('Terminus Dieuppeul', 'Ligne 4', 'DDD'),
('Cité Derklé', 'Ligne 4', 'DDD'),
('Khar Yalla', 'Ligne 4', 'DDD'),
('Cité Marine', 'Ligne 4', 'DDD'),
('CEG Dieuppeul 3', 'Ligne 4', 'DDD'),
('Camp Sapeurs-Pompiers', 'Ligne 4', 'DDD'),
('Cité Sacré Cœur', 'Ligne 4', 'DDD'),
('Collège Sacré Cœur', 'Ligne 4', 'DDD'),
('Sicap Karack', 'Ligne 4', 'DDD'),
('Avenue Bourguiba', 'Ligne 4', 'DDD'),
('Dial Diop ex rue 10', 'Ligne 4', 'DDD'),
('Point E', 'Ligne 4', 'DDD'),
('HLM Fass', 'Ligne 4', 'DDD'),
('Canal Gueule Tapée', 'Ligne 4', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 4', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 4', 'DDD'),
('Boulevard de la République', 'Ligne 4', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 4', 'DDD'),
('Allées Canard-Esso Port Embarcadère', 'Ligne 4', 'DDD'),
('Terminus Leclerc', 'Ligne 4', 'DDD'),
('Terminus Ouakam', 'Ligne 7', 'DDD'),
('Cité Assemblée', 'Ligne 7', 'DDD'),
('Comico', 'Ligne 7', 'DDD'),
('Av Cheikh Anta Diop (route de Ouakam)', 'Ligne 7', 'DDD'),
('avenue Blaise Diagne', 'Ligne 7', 'DDD'),
('avenue Jean Jaurès', 'Ligne 7', 'DDD'),
('avenue André Peytavin', 'Ligne 7', 'DDD'),
('Avenue Georges Pompidou', 'Ligne 7', 'DDD'),
('Place de l’Indépendance', 'Ligne 7', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 7', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 7', 'DDD'),
('Palais de Justice', 'Ligne 7', 'DDD');
INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Aéroport', 'Ligne 8', 'DDD'),
('Cité Asecna', 'Ligne 8', 'DDD'),
('Yoff Village', 'Ligne 8', 'DDD'),
('Stade Léopold Sédar Senghor', 'Ligne 8', 'DDD'),
('Patte d’Oie', 'Ligne 8', 'DDD'),
('Grand Yoff', 'Ligne 8', 'DDD'),
('Cité des Eaux', 'Ligne 8', 'DDD'),
('Avenue Bourguiba', 'Ligne 8', 'DDD'),
('Rue Dial Diop (ex rue 10)', 'Ligne 8', 'DDD'),
('Zone B', 'Ligne 8', 'DDD'),
('Rocade Fann Bel Air (Point E)', 'Ligne 8', 'DDD'),
('Avenue Cheikh Anta Diop (Cité Universitaire)', 'Ligne 8', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 8', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 8', 'DDD'),
('Bld de la République', 'Ligne 8', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 8', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 8', 'DDD'),
('Palais de Justice', 'Ligne 8', 'DDD'),
('Palais 2', 'Ligne 8', 'DDD'),

('Liberté 6', 'Ligne 9', 'DDD'),
('Sacré Cœur', 'Ligne 9', 'DDD'),
('Terminus Dieuppeul', 'Ligne 9', 'DDD'),
('Allées Ababacar Sy', 'Ligne 9', 'DDD'),
('Rondpoint Jet d’Eau', 'Ligne 9', 'DDD'),
('Allées Cheikh Sidate (Niary Tally)', 'Ligne 9', 'DDD'),
('Eglise Sainte Thérèse', 'Ligne 9', 'DDD'),
('Avenue Dial Diop (ex rue 10)', 'Ligne 9', 'DDD'),
('Bld Général De Gaule', 'Ligne 9', 'DDD'),
('Avenue Malick Sy', 'Ligne 9', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 9', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 9', 'DDD'),
('Avenue André Peytavin', 'Ligne 9', 'DDD'),
('Avenue Pompidou', 'Ligne 9', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 9', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 9', 'DDD'),
('Palais 2', 'Ligne 9', 'DDD'),

('Terminus Dieuppeul', 'Ligne 10', 'DDD'),
('Cité Derklé', 'Ligne 10', 'DDD'),
('Khar Yalla', 'Ligne 10', 'DDD'),
('Cité Marine', 'Ligne 10', 'DDD'),
('CEG Dieuppeul 3', 'Ligne 10', 'DDD'),
('Eglise Martyrs de l’Ouganda (rue 11 x P)', 'Ligne 10', 'DDD'),
('Stade Marius Ndiaye', 'Ligne 10', 'DDD'),
('Avenue Bourguiba', 'Ligne 10', 'DDD'),
('Relais', 'Ligne 10', 'DDD'),
('Avenue Cheikh Anta Diop', 'Ligne 10', 'DDD'),
('Rue Aimé Césaire', 'Ligne 10', 'DDD'),
('Corniche Ouest', 'Ligne 10', 'DDD'),
('Village Artisanal de Soumbédioune', 'Ligne 10', 'DDD'),
('Prison Central', 'Ligne 10', 'DDD'),
('Bld de la République', 'Ligne 10', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 10', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 10', 'DDD'),
('Palais 2', 'Ligne 10', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Keur Massar', 'Ligne 11', 'DDD'),
('Parcelles Assainies (keur Massar) Route de Boune', 'Ligne 11', 'DDD'),
('Fass Mbao', 'Ligne 11', 'DDD'),
('Diamaguène', 'Ligne 11', 'DDD'),
('Thiaroye/mer', 'Ligne 11', 'DDD'),
('Croisement Pikine', 'Ligne 11', 'DDD'),
('Route Nationale', 'Ligne 11', 'DDD'),
('Autoroute', 'Ligne 11', 'DDD'),
('Corniche des Hlm', 'Ligne 11', 'DDD'),
('Colobane', 'Ligne 11', 'DDD'),
('Caisse de sécurité sociale', 'Ligne 11', 'DDD'),
('Bd Général De Gaule (Centenaire)', 'Ligne 11', 'DDD'),
('RTS', 'Ligne 11', 'DDD'),
('Rond Point Poste Médina', 'Ligne 11', 'DDD'),
('Blaise Diagne', 'Ligne 11', 'DDD'),
('Sandaga', 'Ligne 11', 'DDD'),
('Terminus Lat-Dior', 'Ligne 11', 'DDD'),
('Lat Dior', 'Ligne 11', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Dieuppeul', 'Ligne 18', 'DDD'),
('Cité Derklé', 'Ligne 18', 'DDD'),
('Khar Yalla', 'Ligne 18', 'DDD'),
('Cité Marine', 'Ligne 18', 'DDD'),
('Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)', 'Ligne 18', 'DDD'),
('Station Castors', 'Ligne 18', 'DDD'),
('Cité Port', 'Ligne 18', 'DDD'),
('Rocade Fann Bel Air', 'Ligne 18', 'DDD'),
('Colobane', 'Ligne 18', 'DDD'),
('Police Bel Air', 'Ligne 18', 'DDD'),
('Grand Moulin de Dakar', 'Ligne 18', 'DDD'),
('Quai de pêche', 'Ligne 18', 'DDD'),
('Esso Port', 'Ligne 18', 'DDD'),
('Place de l’Indépendance', 'Ligne 18', 'DDD'),
('Avenue Georges Pompidou', 'Ligne 18', 'DDD'),
('Avenue André Peytavin', 'Ligne 18', 'DDD'),
('Route de la Corniche', 'Ligne 18', 'DDD'),
('Avenue Malick Sy', 'Ligne 18', 'DDD'),
('Rue 6', 'Ligne 18', 'DDD'),
('Gueule Tapée', 'Ligne 18', 'DDD'),
('Lycée Delafosse', 'Ligne 18', 'DDD'),
('Avenue Cheikh Anta Diop', 'Ligne 18', 'DDD'),
('Ecole Normale Supérieure', 'Ligne 18', 'DDD'),
('Avenue Bourguiba', 'Ligne 18', 'DDD'),
('Rond-Point Jet d’eau', 'Ligne 18', 'DDD'),
('Allées Ababacar Sy', 'Ligne 18', 'DDD'),
('Terminus Dieuppeul', 'Ligne 18', 'DDD'),

('Terminus Dieuppeul', 'Ligne 20', 'DDD'),
('Allées Ababacar Sy', 'Ligne 20', 'DDD'),
('Jet d’eau', 'Ligne 20', 'DDD'),
('Avenue Bourguiba', 'Ligne 20', 'DDD'),
('Ecole Police (Relais)', 'Ligne 20', 'DDD'),
('Avenue Cheikh Anta Diop', 'Ligne 20', 'DDD'),
('Hôpital Fann', 'Ligne 20', 'DDD'),
('Cité Universitaire', 'Ligne 20', 'DDD'),
('Lycée Delafosse', 'Ligne 20', 'DDD'),
('HLM Gueule Tapée', 'Ligne 20', 'DDD'),
('Rue 6', 'Ligne 20', 'DDD'),
('Avenue Malick Sy', 'Ligne 20', 'DDD'),
('Corniche Ouest', 'Ligne 20', 'DDD'),
('Avenue Peytavin', 'Ligne 20', 'DDD'),
('Avenue Pompidou', 'Ligne 20', 'DDD'),
('Place de l’Indépendance', 'Ligne 20', 'DDD'),
('Esso Port', 'Ligne 20', 'DDD'),
('Bld de l’Arsenal', 'Ligne 20', 'DDD'),
('Central Bel Air (MTOA)', 'Ligne 20', 'DDD'),
('Grands Moulin de Dakar', 'Ligne 20', 'DDD'),
('Police Bel Air', 'Ligne 20', 'DDD'),
('Colobane', 'Ligne 20', 'DDD'),
('Angle Colobane', 'Ligne 20', 'DDD'),
('Rue 13 prolongée', 'Ligne 20', 'DDD'),
('Station Castors', 'Ligne 20', 'DDD'),
('Avenue Cheikh Ahmadou Bamba', 'Ligne 20', 'DDD'),
('Cité Port', 'Ligne 20', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus des Parcelles', 'Ligne 23', 'DDD'),
('Ecole Dior', 'Ligne 23', 'DDD'),
('Cités Diamalaye', 'Ligne 23', 'DDD'),
('Hlm Grand Médine', 'Ligne 23', 'DDD'),
('Reprise Route du Terminus', 'Ligne 23', 'DDD'),
('Eglise', 'Ligne 23', 'DDD'),
('Route des Niayes', 'Ligne 23', 'DDD'),
('Echangeur du Stade LÃ©opold SÃ©dar Senghor (AmitiÃ©)', 'Ligne 23', 'DDD'),
('Cité Keur Khadim', 'Ligne 23', 'DDD'),
('Camp Pénal', 'Ligne 23', 'DDD'),
('Route du Front de Terre', 'Ligne 23', 'DDD'),
('Cité des Eaux', 'Ligne 23', 'DDD'),
('Avenue Bourguiba', 'Ligne 23', 'DDD'),
('Relais', 'Ligne 23', 'DDD'),
('Avenue Cheikh Anta Diop', 'Ligne 23', 'DDD'),
('(Route de Ouakam)', 'Ligne 23', 'DDD'),
('Marché SAHM', 'Ligne 23', 'DDD'),
('Gueule Tapée', 'Ligne 23', 'DDD'),
('Rue 6', 'Ligne 23', 'DDD'),
('Avenue Malick Sy', 'Ligne 23', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 23', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 23', 'DDD'),
('Bld de la République', 'Ligne 23', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 23', 'DDD'),
('Hôpital Principal', 'Ligne 23', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 23', 'DDD'),
('Hôpital Le Dantec', 'Ligne 23', 'DDD'),
('Palais de Justice', 'Ligne 23', 'DDD'),
('Palais 1', 'Ligne 23', 'DDD');


INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Rufisque', 'Ligne 15A & 15B', 'DDD'),
('Mosquée Keuri Kaw', 'Ligne 15A & 15B', 'DDD'),
('Sortie Rufisque (Dioukoul)', 'Ligne 15A & 15B', 'DDD'),
('Sicap Mbao', 'Ligne 15A & 15B', 'DDD'),
('Diamaguène', 'Ligne 15A & 15B', 'DDD'),
('Croisement Pikine', 'Ligne 15A & 15B', 'DDD'),
('Route de Rufisque', 'Ligne 15A & 15B', 'DDD'),
('SCOA', 'Ligne 15A & 15B', 'DDD'),
('SONACOS', 'Ligne 15A & 15B', 'DDD'),
('Bld de l’Arsenal', 'Ligne 15A & 15B', 'DDD'),
('Esso Port', 'Ligne 15A & 15B', 'DDD'),
('Place de l’Indépendance', 'Ligne 15A & 15B', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 15A & 15B', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 15A & 15B', 'DDD'),
('Palais 1', 'Ligne 15A & 15B', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Terminus Malika', 'Ligne 16A', 'DDD'),
('Yeumbeul', 'Ligne 16A', 'DDD'),
('Tally Diallo', 'Ligne 16A', 'DDD'),
('Icotaf', 'Ligne 16A', 'DDD'),
('Cité Lobatt Fall', 'Ligne 16A', 'DDD'),
('Rond-point Lobatt Fall', 'Ligne 16A', 'DDD'),
('Autoroute', 'Ligne 16A', 'DDD'),
('Colobane', 'Ligne 16A', 'DDD'),
('Rond-point Colobane', 'Ligne 16A', 'DDD'),
('Place Bakou', 'Ligne 16A', 'DDD'),
('Cfao Technologies', 'Ligne 16A', 'DDD'),
('Cyrnos', 'Ligne 16A', 'DDD'),
('Arsenal', 'Ligne 16A', 'DDD'),
('Place de l’Indépendance', 'Ligne 16A', 'DDD'),
('Palais de justice 1', 'Ligne 16A', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Terminus Malika', 'Ligne 16B', 'DDD'),
('Station Keur Massar', 'Ligne 16B', 'DDD'),
('Croisement Keur Massar', 'Ligne 16B', 'DDD'),
('LGI Mbao', 'Ligne 16B', 'DDD'),
('Diamaguène', 'Ligne 16B', 'DDD'),
('Thiaroye', 'Ligne 16B', 'DDD'),
('Sips', 'Ligne 16B', 'DDD'),
('Sotiba (seras)', 'Ligne 16B', 'DDD'),
('Yarakh', 'Ligne 16B', 'DDD'),
('Capa Virmaud', 'Ligne 16B', 'DDD'),
('Place Bakou', 'Ligne 16B', 'DDD'),
('(Scoa)', 'Ligne 16B', 'DDD'),
('Police Bel Air', 'Ligne 16B', 'DDD'),
('Bel Air', 'Ligne 16B', 'DDD'),
('GMD', 'Ligne 16B', 'DDD'),
('Sofrigal (môle 8)', 'Ligne 16B', 'DDD'),
('Cyrnos (sur le pont)', 'Ligne 16B', 'DDD'),
('Caserne Sapeurs Pompiers', 'Ligne 16B', 'DDD'),
('Avenue Lamine Guèye (Sandaga)', 'Ligne 16B', 'DDD'),
('Avenue André Peytavin', 'Ligne 16B', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 16B', 'DDD'),
('Boulevard de la République', 'Ligne 16B', 'DDD'),
('Avenue Léopold Sédar Senghor (Roume)', 'Ligne 16B', 'DDD'),
('Hôpital Principal', 'Ligne 16B', 'DDD'),
('Assemblée Nationale', 'Ligne 16B', 'DDD'),
('Hôpital Le Dantec', 'Ligne 16B', 'DDD'),
('Palais 1', 'Ligne 16B', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Gorom 01', 'Ligne 208', 'DDD'),
('Gororm 02', 'Ligne 208', 'DDD'),
('Bambilor', 'Ligne 208', 'DDD'),
('Noflaye', 'Ligne 208', 'DDD'),
('Sangalkam', 'Ligne 208', 'DDD'),
('Keur Ndiaye Lo', 'Ligne 208', 'DDD'),
('Rufisque', 'Ligne 208', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Rufisque', 'Ligne 213', 'DDD'),
('Dieuppeul', 'Ligne 213', 'DDD'),
('Gare de Rufisque', 'Ligne 213', 'DDD'),
('HLM SIPRES', 'Ligne 213', 'DDD'),
('ZAC Mbao', 'Ligne 213', 'DDD'),
('Grand Mbao', 'Ligne 213', 'DDD'),
('Stade Mbao', 'Ligne 213', 'DDD'),
('Petit Mbao', 'Ligne 213', 'DDD'),
('Croisement Petit Mbao', 'Ligne 213', 'DDD'),
('RN1', 'Ligne 213', 'DDD'),
('poste Thiaroye', 'Ligne 213', 'DDD'),
('péage', 'Ligne 213', 'DDD'),
('sortie Cambérène', 'Ligne 213', 'DDD'),
('Patte d’Oie', 'Ligne 213', 'DDD'),
('Marche Grand Yoff', 'Ligne 213', 'DDD'),
('Police Grand Yoff', 'Ligne 213', 'DDD'),
('Rond-Point Liberté 6', 'Ligne 213', 'DDD'),
('Terminus Dieuppeul', 'Ligne 213', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Thiaroye', 'Ligne 217', 'DDD'),
('Ouakam', 'Ligne 217', 'DDD'),
('Dépôt Thiaroye', 'Ligne 217', 'DDD'),
('police Thiaroye', 'Ligne 217', 'DDD'),
('Route des Niayes', 'Ligne 217', 'DDD'),
('Pikine', 'Ligne 217', 'DDD'),
('Canada Golf Fadia', 'Ligne 217', 'DDD'),
('Case bi', 'Ligne 217', 'DDD'),
('Croisement 22', 'Ligne 217', 'DDD'),
('Eglise', 'Ligne 217', 'DDD'),
('Terminus parcelles Assainies', 'Ligne 217', 'DDD'),
('Dior Centre Bceao', 'Ligne 217', 'DDD'),
('Route cimetière Yoff', 'Ligne 217', 'DDD'),
('Route de L’Aéroport', 'Ligne 217', 'DDD'),
('Ngor– route des Almadies', 'Ligne 217', 'DDD'),
('Mamelles', 'Ligne 217', 'DDD'),
('Marché Ouakam', 'Ligne 217', 'DDD'),
('Terminus Ouakam', 'Ligne 217', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Dépôt Thiaroye', 'Ligne 218', 'DDD'),
('Route Nationale N° 1', 'Ligne 218', 'DDD'),
('Pikine', 'Ligne 218', 'DDD'),
('patte d’oies', 'Ligne 218', 'DDD'),
('Foire', 'Ligne 218', 'DDD'),
('VDN', 'Ligne 218', 'DDD'),
('Sipres', 'Ligne 218', 'DDD'),
('ancienne piste', 'Ligne 218', 'DDD'),
('Ouakam', 'Ligne 218', 'DDD'),
('marché Ouakam', 'Ligne 218', 'DDD'),
('terminus Ouakam', 'Ligne 218', 'DDD'),
('route des mamelles', 'Ligne 218', 'DDD'),
('route des Almadies', 'Ligne 218', 'DDD'),
('Ngor', 'Ligne 218', 'DDD'),
('Terminus aéroport LSS', 'Ligne 218', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Daroukhane', 'Ligne 219', 'DDD'),
('marché Ndiarème', 'Ligne 219', 'DDD'),
('deux voies Pikine Notaire', 'Ligne 219', 'DDD'),
('Terminus Guédiawaye', 'Ligne 219', 'DDD'),
('Stade Amadou Barry', 'Ligne 219', 'DDD'),
('Marché Sham', 'Ligne 219', 'DDD'),
('Marché Jeudi corniche', 'Ligne 219', 'DDD'),
('Croisement Béthio', 'Ligne 219', 'DDD'),
('Fadia', 'Ligne 219', 'DDD'),
('Case bi', 'Ligne 219', 'DDD'),
('Pont Sénégal 92', 'Ligne 219', 'DDD'),
('Collège Hyacinthe Thiandoum', 'Ligne 219', 'DDD'),
('Deux voies liberté 6', 'Ligne 219', 'DDD'),
('Ancienne Piste', 'Ligne 219', 'DDD'),
('Hôpital militaire de Ouakam', 'Ligne 219', 'DDD'),
('Comico', 'Ligne 219', 'DDD'),
('Cité Asecna', 'Ligne 219', 'DDD'),
('Cité Assemblée', 'Ligne 219', 'DDD'),
('Terminus Ouakam', 'Ligne 219', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Rufisque', 'Ligne 220', 'DDD'),
('Guédiawaye', 'Ligne 220', 'DDD'),
('Terminus Rufisque', 'Ligne 220', 'DDD'),
('Djoutiba', 'Ligne 220', 'DDD'),
('HLM Rufisque', 'Ligne 220', 'DDD'),
('SIPRES', 'Ligne 220', 'DDD'),
('SEDIMA', 'Ligne 220', 'DDD'),
('Lycée Jaxaay-2 voies', 'Ligne 220', 'DDD'),
('Jaxaay', 'Ligne 220', 'DDD'),
('Station Keur Massar', 'Ligne 220', 'DDD'),
('Terminus Malika', 'Ligne 220', 'DDD'),
('Malika Plage', 'Ligne 220', 'DDD'),
('Sortie Autoroute', 'Ligne 220', 'DDD'),
('Serigne Assane', 'Ligne 220', 'DDD'),
('Lycée Limamoulaye', 'Ligne 220', 'DDD'),
('Terminus Guédiawaye', 'Ligne 220', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Cité Gadaye (Filaos)', 'Ligne 221', 'DDD'),
('Corniche Daroukhane', 'Ligne 221', 'DDD'),
('Hamo 6', 'Ligne 221', 'DDD'),
('Arrêt Dial Mbaye', 'Ligne 221', 'DDD'),
('PAI', 'Ligne 221', 'DDD'),
('Dalal Diam', 'Ligne 221', 'DDD'),
('Case', 'Ligne 221', 'DDD'),
('Police PA', 'Ligne 221', 'DDD'),
('Pont Sénégal emergent', 'Ligne 221', 'DDD'),
('Route de l’aéroport', 'Ligne 221', 'DDD'),
('Yoff Tonghor', 'Ligne 221', 'DDD'),
('Cite Asecna', 'Ligne 221', 'DDD'),
('Rond-point Ngor', 'Ligne 221', 'DDD'),
('Ngor village', 'Ligne 221', 'DDD'),
('Almadies', 'Ligne 221', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Keur Massar', 'Ligne 227', 'DDD'),
('Terminus Parcelles', 'Ligne 227', 'DDD'),
('Terminus Keur Massar', 'Ligne 227', 'DDD'),
('Station Keur Massar', 'Ligne 227', 'DDD'),
('Hôpital Keur Massar', 'Ligne 227', 'DDD'),
('Keur Massar', 'Ligne 227', 'DDD'),
('Terminus Malika', 'Ligne 227', 'DDD'),
('Malika plage', 'Ligne 227', 'DDD'),
('Sortie autoroute', 'Ligne 227', 'DDD'),
('Stade amadou Barry', 'Ligne 227', 'DDD'),
('CES Canada', 'Ligne 227', 'DDD'),
('Pharmacie Golf', 'Ligne 227', 'DDD'),
('Fadia', 'Ligne 227', 'DDD'),
('Case bi', 'Ligne 227', 'DDD'),
('Croisement 22', 'Ligne 227', 'DDD'),
('Eglise PA', 'Ligne 227', 'DDD'),
('Terminus Parcelles', 'Ligne 227', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Terminus Rufisque', 'Ligne 228', 'DDD'),
('ville de Rufisque', 'Ligne 228', 'DDD'),
('Bargny', 'Ligne 228', 'DDD'),
('Diamniadio Yenne', 'Ligne 228', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Baux Maraichers', 'Ligne 232', 'DDD'),
('Yarakh', 'Ligne 232', 'DDD'),
('Cafétéria', 'Ligne 232', 'DDD'),
('Hann Maristes', 'Ligne 232', 'DDD'),
('Cours Sainte Marie de Hann', 'Ligne 232', 'DDD'),
('Usine des eaux', 'Ligne 232', 'DDD'),
('Front de terre', 'Ligne 232', 'DDD'),
('Khar Yalla', 'Ligne 232', 'DDD'),
('Rond-Point Liberté 6', 'Ligne 232', 'DDD'),
('deux voies vers Camp Leclerc', 'Ligne 232', 'DDD'),
('Foire', 'Ligne 232', 'DDD'),
('Itinéraire ligne 8', 'Ligne 232', 'DDD'),
('Terminus Aéroport LSS', 'Ligne 232', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Baux Maraichers', 'Ligne 233', 'DDD'),
('RN1', 'Ligne 233', 'DDD'),
('Croisement Cambérène', 'Ligne 233', 'DDD'),
('Mariste', 'Ligne 233', 'DDD'),
('Castors', 'Ligne 233', 'DDD'),
('Itinéraire ligne13', 'Ligne 233', 'DDD'),
('Rond-point maison PS', 'Ligne 233', 'DDD'),
('Hampathé Ba', 'Ligne 233', 'DDD'),
('Cité Claudel', 'Ligne 233', 'DDD'),
('Immeuble Dieze', 'Ligne 233', 'DDD'),
('Rue 6', 'Ligne 233', 'DDD'),
('Malick Sy', 'Ligne 233', 'DDD'),
('Poste Médine', 'Ligne 233', 'DDD'),
('Ave Blaise Diagne', 'Ligne 233', 'DDD'),
('Avenue Peytavin', 'Ligne 233', 'DDD'),
('Ponty', 'Ligne 233', 'DDD'),
('Place de l’Indépendance', 'Ligne 233', 'DDD'),
('Hôpital Principal', 'Ligne 233', 'DDD'),
('Hôpital Le Dantec', 'Ligne 233', 'DDD'),
('Palais 1', 'Ligne 233', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Jaxaay', 'Ligne 234', 'DDD'),
('Leclerc', 'Ligne 234', 'DDD'),
('Mosquée Niakoul Rab', 'Ligne 234', 'DDD'),
('Ecole Panthéon', 'Ligne 234', 'DDD'),
('2 voies Jaxaay', 'Ligne 234', 'DDD'),
('Station Keur Massar', 'Ligne 234', 'DDD'),
('Croisement Keur Massar', 'Ligne 234', 'DDD'),
('Fass Mbao', 'Ligne 234', 'DDD'),
('Diamagueune', 'Ligne 234', 'DDD'),
('Poste Thiaroye', 'Ligne 234', 'DDD'),
('Autoroute', 'Ligne 234', 'DDD'),
('Péage', 'Ligne 234', 'DDD'),
('AIBD', 'Ligne 234', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Terminus Ouakam', 'Ligne 401', 'DDD'),
('Mamelles', 'Ligne 401', 'DDD'),
('Croisement Almadies', 'Ligne 401', 'DDD'),
('Ngor', 'Ligne 401', 'DDD'),
('Yoff', 'Ligne 401', 'DDD'),
('Rte de l’Aéroport', 'Ligne 401', 'DDD'),
('Foire', 'Ligne 401', 'DDD'),
('VDN', 'Ligne 401', 'DDD'),
('Direction Générale DDD', 'Ligne 401', 'DDD'),
('Rond-Point JVC', 'Ligne 401', 'DDD'),
('Rond-Point Liberté 6', 'Ligne 401', 'DDD'),
('Itinéraire 213', 'Ligne 401', 'DDD'),
('Police Grand Yoff', 'Ligne 401', 'DDD'),
('Pharmacie Patte d’Oie', 'Ligne 401', 'DDD'),
('Terminus Sphère', 'Ligne 401', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Thiaroye', 'Ligne 402', 'DDD'),
('RN1', 'Ligne 402', 'DDD'),
('Rufisque Ouest', 'Ligne 402', 'DDD'),
('Bargny', 'Ligne 402', 'DDD'),
('Diamniadio', 'Ligne 402', 'DDD'),
('AIBD', 'Ligne 402', 'DDD'),
('Thiaroye', 'Ligne 402', 'DDD'),
('RN1', 'Ligne 402', 'DDD'),
('Rufisque Ouest', 'Ligne 402', 'DDD'),
('Bargny', 'Ligne 402', 'DDD'),
('Diamniadio', 'Ligne 402', 'DDD'),
('Sphère', 'Ligne 402', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES

('Terminus Dieuppeul', 'Ligne 13', 'DDD'),
('Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée)', 'Ligne 13', 'DDD'),
('Station Castors', 'Ligne 13', 'DDD'),
('Cité Port', 'Ligne 13', 'DDD'),
('Lycée Kennedy', 'Ligne 13', 'DDD'),
('Bld Général De Gaule', 'Ligne 13', 'DDD'),
('Allées Papa Guèye Fall', 'Ligne 13', 'DDD'),
('Avenue Faidherbe', 'Ligne 13', 'DDD'),
('Esso Port', 'Ligne 13', 'DDD'),
('Place de l’Indépendance', 'Ligne 13', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 13', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 13', 'DDD'),
('Palais 2', 'Ligne 13', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Daroukhane', 'Ligne 2', 'DDD'),
('Corniche-Hamo', 'Ligne 2', 'DDD'),
('Terminus Guédiawaye', 'Ligne 2', 'DDD'),
('Marché Sahm', 'Ligne 2', 'DDD'),
('Ecole Canada', 'Ligne 2', 'DDD'),
('Route des Niayes', 'Ligne 2', 'DDD'),
('Tally Boumack (route de l’Ouest)', 'Ligne 2', 'DDD'),
('Route Nationale n° 1', 'Ligne 2', 'DDD'),
('Autoroute', 'Ligne 2', 'DDD'),
('Cité des Eaux', 'Ligne 2', 'DDD'),
('Avenue Bourguiba', 'Ligne 2', 'DDD'),
('Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée)', 'Ligne 2', 'DDD'),
('Bld Général De Gaule', 'Ligne 2', 'DDD'),
('Rue 25', 'Ligne 2', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 2', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 2', 'DDD'),
('Avenue Georges Pompidou', 'Ligne 2', 'DDD'),
('Place de l’Indépendance', 'Ligne 2', 'DDD'),
('Esso Port', 'Ligne 2', 'DDD'),
('Place Leclerc', 'Ligne 2', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Cambéréne 2', 'Ligne 6', 'DDD'),
('Cambéréne village', 'Ligne 6', 'DDD'),
('Case', 'Ligne 6', 'DDD'),
('Route des Niayes', 'Ligne 6', 'DDD'),
('Police des Parcelles Assainies', 'Ligne 6', 'DDD'),
('Marché Grand-Médine', 'Ligne 6', 'DDD'),
('Cité Keur Damel', 'Ligne 6', 'DDD'),
('VDN Sipres', 'Ligne 6', 'DDD'),
('Camp Pénal', 'Ligne 6', 'DDD'),
('Derklé', 'Ligne 6', 'DDD'),
('Liberté 5', 'Ligne 6', 'DDD'),
('Allées Khalifa Ababacar Sy', 'Ligne 6', 'DDD'),
('Jet d’Eau', 'Ligne 6', 'DDD'),
('Niary Tally', 'Ligne 6', 'DDD'),
('Enam', 'Ligne 6', 'DDD'),
('Bld Général De Gaule', 'Ligne 6', 'DDD'),
('Allées Papa Guèye Fall', 'Ligne 6', 'DDD'),
('Avenue Faidherbe', 'Ligne 6', 'DDD'),
('Avenue Lamine Guèye', 'Ligne 6', 'DDD'),
('Avenue André Peytavin', 'Ligne 6', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 6', 'DDD'),
('Bld de la République', 'Ligne 6', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 6', 'DDD'),
('Palais 2', 'Ligne 6', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Guédiawaye', 'Ligne 5', 'DDD'),
('Route de la Corniche', 'Ligne 5', 'DDD'),
('Cité des Enseignants', 'Ligne 5', 'DDD'),
('Maison du PAI', 'Ligne 5', 'DDD'),
('Cité Hlm', 'Ligne 5', 'DDD'),
('Golf', 'Ligne 5', 'DDD'),
('Route des Niayes', 'Ligne 5', 'DDD'),
('Police de Parcelles Assainies', 'Ligne 5', 'DDD'),
('Pont du Stade Léopold Sédar Senghor (Echangeur)', 'Ligne 5', 'DDD'),
('Patte d’Oie', 'Ligne 5', 'DDD'),
('Autoroute', 'Ligne 5', 'DDD'),
('Passage Cyrnos', 'Ligne 5', 'DDD'),
('Avenue Lamine Guèye', 'Ligne 5', 'DDD'),
('Avenue André Peytavin', 'Ligne 5', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 5', 'DDD'),
('Bld de la République', 'Ligne 5', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 5', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 5', 'DDD'),
('Palais de Justice 1', 'Ligne 5', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('PA', 'Ligne 403', 'DDD'),
('Hôpital Dalal Diam', 'Ligne 403', 'DDD'),
('Itinéraire 227', 'Ligne 403', 'DDD'),
('2 voies Jaxaay', 'Ligne 403', 'DDD'),
('Sedima', 'Ligne 403', 'DDD'),
('Péage', 'Ligne 403', 'DDD'),
('AIBD', 'Ligne 403', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Leclerc', 'Ligne 404A', 'DDD'),
('Ave Albert Sarraut', 'Ligne 404A', 'DDD'),
('Itinéraire ligne 13', 'Ligne 404A', 'DDD'),
('Colobane', 'Ligne 404A', 'DDD'),
('Autoroute à Péage', 'Ligne 404A', 'DDD'),
('Diamniadio', 'Ligne 404A', 'DDD'),
('Itinéraire ligne 228', 'Ligne 404A', 'DDD'),
('Diass', 'Ligne 404A', 'DDD'),
('Croisement Kiréne', 'Ligne 404A', 'DDD'),
('Croisement zone fret', 'Ligne 404A', 'DDD'),
('AIBD', 'Ligne 404A', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Leclerc', 'Ligne 404B', 'DDD'),
('Ave Albert Sarraut', 'Ligne 404B', 'DDD'),
('Itinéraire ligne 13', 'Ligne 404B', 'DDD'),
('Colobane', 'Ligne 404B', 'DDD'),
('Autoroute à Péage', 'Ligne 404B', 'DDD'),
('Poste Thiaroye', 'Ligne 404B', 'DDD'),
('itinéraire ligne 402', 'Ligne 404B', 'DDD'),
('AIBD', 'Ligne 404B', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Dieuppeul', 'Ligne 405', 'DDD'),
('Jet D’eau', 'Ligne 405', 'DDD'),
('Bourguiba', 'Ligne 405', 'DDD'),
('Allées Seydou Nourou Tall', 'Ligne 405', 'DDD'),
('Canal 4', 'Ligne 405', 'DDD'),
('Autoroute', 'Ligne 405', 'DDD'),
('Péage', 'Ligne 405', 'DDD'),
('AIBD', 'Ligne 405', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES
('Guédiawaye', 'Ligne 12', 'DDD'),
('Cité des Enseignants', 'Ligne 12', 'DDD'),
('Maison du PAI', 'Ligne 12', 'DDD'),
('Hlm Guédiawaye', 'Ligne 12', 'DDD'),
('Domaine de Guédiawaye', 'Ligne 12', 'DDD'),
('Lycée Canada', 'Ligne 12', 'DDD'),
('Route des Niayes', 'Ligne 12', 'DDD'),
('Tally Boubess', 'Ligne 12', 'DDD'),
('Marché poissons', 'Ligne 12', 'DDD'),
('Route de Rufisque', 'Ligne 12', 'DDD'),
('Capa', 'Ligne 12', 'DDD'),
('TP Cap Vert', 'Ligne 12', 'DDD'),
('Cité des Eaux', 'Ligne 12', 'DDD'),
('Avenue Bourguiba', 'Ligne 12', 'DDD'),
('Relais Avenue Cheikh Anta Diop (Hôpital Fann)', 'Ligne 12', 'DDD'),
('Avenue Blaise Diagne', 'Ligne 12', 'DDD'),
('Avenue Jean Jaurès', 'Ligne 12', 'DDD'),
('Bld de la République', 'Ligne 12', 'DDD'),
('Avenue Léopold Sédar Senghor', 'Ligne 12', 'DDD'),
('Avenue Nelson Mandela', 'Ligne 12', 'DDD'),
('Palais de Justice', 'Ligne 12', 'DDD');

INSERT INTO bus (nom_long, ligne, type)
VALUES 
('Scat Urbam', 'Ligne 121', 'DDD'),
('Mairie grand Yoff', 'Ligne 121', 'DDD'),
('Cité Cse', 'Ligne 121', 'DDD'),
('Les deux voies de Sipres', 'Ligne 121', 'DDD'),
('Les deux voies de Liberté 6', 'Ligne 121', 'DDD'),
('Collège Sacré Cœur', 'Ligne 121', 'DDD'),
('Sicap rue 10', 'Ligne 121', 'DDD'),
('Lycée Blaise Diagne', 'Ligne 121', 'DDD'),
('Place ONU', 'Ligne 121', 'DDD'),
('Canal 4', 'Ligne 121', 'DDD'),
('HLM Fass', 'Ligne 121', 'DDD'),
('Travaux communaux', 'Ligne 121', 'DDD'),
('Rue 22 prolongée', 'Ligne 121', 'DDD'),
('Rts', 'Ligne 121', 'DDD'),
('Allées Papa Guèye Fall', 'Ligne 121', 'DDD'),
('Avenue Faidherbe', 'Ligne 121', 'DDD'),
('Place de l’indépendance', 'Ligne 121', 'DDD'),
('Albert Sarraut', 'Ligne 121', 'DDD'),
('Terminus Leclerc', 'Ligne 121', 'DDD');
