import requests

# Remplacez "VOTRE_CLE_API" par votre clé d'API Google Maps valide
API_KEY = "AIzaSyBJGDWHfSkHGw8rB7SefORqkSmHF7qX4x4"

# Liste des noms des stations de bus
stations = [
    "Terminus Daroukhane",
    "Corniche-Hamo",
    "Terminus Guédiawaye",
    "Marché Sahm",
    "Ecole Canada",
    "Route des Niayes",
    "Tally Boumack (route de l’Ouest)",
    "Route Nationale n° 1",
    "Autoroute",
    "Cité des Eaux",
    "Avenue Bourguiba",
    "Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée)",
    "Bld Général De Gaule",
    "Rue 25",
    "Avenue Blaise Diagne",
    "Avenue Jean Jaurès",
    "Avenue Georges Pompidou",
    "Place de l’Indépendance",
    "Esso Port",
    "Place Leclerc",
    "Terminus Dieuppeul",
    "Cité Derklé",
    "Khar Yalla",
    "Cité Marine",
    "CEG Dieuppeul 3",
    "Camp Sapeurs-Pompiers",
    "Cité Sacré Cœur",
    "Collège Sacré Cœur",
    "Sicap Karack",
    "Dial Diop ex rue 10",
    "Point E",
    "HLM Fass",
    "Canal Gueule Tapée",
    "Boulevard de la République",
    "Avenue Léopold Sédar Senghor",
    "Allées Canard-Esso Port Embarcadère",
    "Terminus Leclerc",
    "Route de la Corniche",
    "Cité des Enseignants",
    "Maison du PAI",
    "Cité Hlm",
    "Golf",
    "Police de Parcelles Assainies",
    "Pont du Stade Léopold Sédar Senghor (Echangeur)",
    "Patte d’Oie",
    "Passage Cyrnos",
    "Avenue Lamine Guèye",
    "Avenue André Peytavin",
    "Bld de la République",
    "Avenue Nelson Mandela",
    "Palais de Justice 1",
    "Parcelles Assainies",
    "Corniche (U 10-9-15)",
    "Dior",
    "Acapes",
    "Dispensaire Norade",
    "Passage entre U22 et U24",
    "Marché Grand-Médine",
    "VDN",
    "Relais",
    "Avenue Cheikh Anta Diop",
    "Avenue George Pompidou",
    "Allées Canard",
    "Embarcadère",
    "Liberté 5",
    "Terminus Ouakam",
    "Cité Assemblée",
    "Comico",
    "Av Cheikh Anta Diop (route de Ouakam)",
    "Palais de Justice",
    "Terminus Aéroport",
    "Cité Asecna",
    "Yoff Village",
    "Stade Léopold Sédar Senghor",
    "Grand Yoff",
    "Rue Dial Diop (ex rue 10)",
    "Zone B",
    "Rocade Fann Bel Air (Point E)",
    "Avenue Cheikh Anta Diop (Cité Universitaire)",
    "Palais 2",
    "Liberté 6",
    "Sacré Cœur",
    "Allées Ababacar Sy",
    "Rondpoint Jet d’Eau",
    "Allées Cheikh Sidate (Niary Tally)",
    "Eglise Sainte Thérèse",
    "Avenue Dial Diop (ex rue 10)",
    "Avenue Malick Sy",
    "Avenue Pompidou",
    "Eglise Martyrs de l’Ouganda (rue 11 x P)",
    "Stade Marius Ndiaye",
    "Rue Aimé Césaire",
    "Corniche Ouest",
    "Village Artisanal de Soumbédioune",
    "Prison Central",
    "Terminus Keur Massar",
    "Parcelles Assainies (keur Massar) Route de Boune",
    "Fass Mbao",
    "Diamaguène",
    "Thiaroye/mer",
    "Croisement Pikine",
    "Route Nationale",
    "Corniche des Hlm",
    "Colobane",
    "Caisse de sécurité sociale",
    "Bd Général De Gaule (Centenaire)",
    "RTS",
    "Rond Point Poste Médina",
    "Blaise Diagne",
    "Sandaga",
    "Terminus Lat-Dior",
    "Lat Dior",
    "Station Castors",
    "Cité Port",
    "Rocade Fann Bel Air",
    "Police Bel Air",
    "Grand Moulin de Dakar",
    "Quai de pêche",
    "Rue 6",
    "Gueule Tapée",
    "Lycée Delafosse",
    "Ecole Normale Supérieure",
    "Rond-Point Jet d’eau",
    "Jet d’eau",
    "Ecole Police (Relais)",
    "Hôpital Fann",
    "Cité Universitaire",
    "HLM Gueule Tapée",
    "Avenue Peytavin",
    "Bld de l’Arsenal",
    "Central Bel Air (MTOA)",
    "Grands Moulin de Dakar",
    "Angle Colobane",
    "Rue 13 prolongée",
    "Avenue Cheikh Ahmadou Bamba",
    "Terminus des Parcelles",
    "Ecole Dior",
    "Cités Diamalaye",
    "Hlm Grand Médine",
    "Reprise Route du Terminus",
    "Eglise",
    "Echangeur du Stade Léopold Sédar Senghor (Amitié)",
    "Cité Keur Khadim",
    "Camp Pénal",
    "Route du Front de Terre (Route de Ouakam)",
    "Hôpital Principal",
    "Hôpital Le Dantec",
    "Palais 1",
    "Terminus Rufisque",
    "Mosquée Keuri Kaw",
    "Sortie Rufisque (Dioukoul)",
    "Sicap Mbao",
    "Route de Rufisque",
    "SCOA",
    "SONACOS",
    "Terminus Malika",
    "Yeumbeul",
    "Tally Diallo",
    "Icotaf",
    "Cité Lobatt Fall",
    "Rond-point Lobatt Fall",
    "Rond-point Colobane",
    "Place Bakou",
    "Cfao Technologies",
    "Cyrnos",
    "Arsenal",
    "Station Keur Massar",
    "Croisement Keur Massar",
    "LGI Mbao",
    "Thiaroye",
    "Sips",
    "Sotiba (seras)",
    "Yarakh",
    "Capa Virmaud (Scoa)",
    "Bel Air",
    "GMD",
    "Sofrigal (môle 8)",
    "Cyrnos (sur le pont)",
    "Caserne Sapeurs Pompiers",
    "Avenue Lamine Guèye (Sandaga)",
    "Avenue Léopold Sédar Senghor (Roume)",
    "Assemblée Nationale",
    "Gorom 01",
    "Gororm 02",
    "Bambilor",
    "Noflaye",
    "Sangalkam",
    "Keur Ndiaye Lo",
    "Rufisque",
    "Dieuppeul",
    "Gare de Rufisque",
    "HLM SIPRES",
    "ZAC Mbao",
    "Grand Mbao",
    "Stade Mbao",
    "Petit Mbao",
    "Croisement Petit Mbao",
    "RN1",
    "poste Thiaroye",
    "péage",
    "sortie Cambérène",
    "Marche Grand Yoff",
    "Police Grand Yoff",
    "Rond-Point Liberté 6",
    "Ouakam",
    "Dépôt Thiaroye",
    "police Thiaroye",
    "Pikine",
    "Canada Golf Fadia",
    "Case bi",
    "Croisement 22",
    "Terminus Parcelles Assainies",
    "Dior Centre Bceao",
    "Route cimetière Yoff",
    "Route de L’Aéroport",
    "Ngor– route des Almadies",
    "Mamelles",
    "Marché Ouakam",
    "patte d’oies",
    "Foire",
    "Sipres",
    "ancienne piste",
    "route des mamelles",
    "route des Almadies",
    "Ngor",
    "Terminus aéroport LSS",
    "Daroukhane",
    "marché Ndiarème",
    "deux voies Pikine Notaire",
    "Stade Amadou Barry",
    "Marché Sham",
    "Marché Jeudi corniche",
    "Croisement Béthio",
    "Fadia",
    "Pont Sénégal 92",
    "Collège Hyacinthe Thiandoum",
    "Deux voies liberté 6",
    "Hôpital militaire de Ouakam",
    "Guédiawaye",
    "Djoutiba",
    "HLM Rufisque",
    "SEDIMA",
    "Lycée Jaxaay-2 voies",
    "Jaxaay",
    "Malika Plage",
    "Sortie Autoroute",
    "Serigne Assane",
    "Lycée Limamoulaye",
    "Cité Gadaye (Filaos)",
    "Corniche Daroukhane",
    "Hamo 6",
    "Arrêt Dial Mbaye",
    "PAI",
    "Dalal Diam",
    "Case",
    "Police PA",
    "Pont Sénégal emergent",
    "Yoff Tonghor",
    "Rond-point Ngor",
    "Ngor village",
    "Almadies",
    "Terminus Parcelles",
    "Hôpital Keur Massar",
    "Keur Massar",
    "CES Canada",
    "Pharmacie Golf",
    "Eglise PA",
    "ville de Rufisque",
    "Bargny",
    "Diamniadio Yenne",
    "Baux Maraichers",
    "Cafétéria",
    "Hann Maristes",
    "Cours Sainte Marie de Hann",
    "Usine des eaux",
    "Front de terre",
    "deux voies vers Camp Leclerc",
    "Itinéraire ligne 8",
    "Croisement Cambérène",
    "Mariste",
    "Castors",
    "Itinéraire ligne13",
    "Rond-point maison PS",
    "Hampathé Ba",
    "Cité Claudel",
    "Immeuble Dieze",
    "Malick Sy",
    "Poste Médine",
    "Ave Blaise Diagne",
    "Ponty",
    "Leclerc",
    "Mosquée Niakoul Rab",
    "Ecole Panthéon",
    "2 voies Jaxaay",
    "Diamagueune",
    "AIBD",
    "Croisement Almadies",
    "Yoff",
    "Rte de l’Aéroport",
    "Direction Générale DDD",
    "Rond-Point JVC",
    "Itinéraire 213",
    "Pharmacie Patte d’Oie",
    "Terminus Sphère",
    "Rufisque Ouest",
    "Diamniadio",
    "Sphère",
    "Lycée Kennedy",
    "Allées Papa Guèye Fall",
    "Avenue Faidherbe",
    "Cambéréne 2",
    "Cambéréne village",
    "Police des Parcelles Assainies",
    "Cité Keur Damel",
    "VDN Sipres",
    "Derklé",
    "Allées Khalifa Ababacar Sy",
    "Niary Tally",
    "Enam",
    "PA",
    "Hôpital Dalal Diam",
    "Itinéraire 227",
    "Ave Albert Sarraut",
    "Itinéraire ligne 13",
    "Autoroute à Péage",
    "Itinéraire ligne 228",
    "Diass",
    "Croisement Kiréne",
    "Croisement zone fret",
    "itinéraire ligne 402",
    "Bourguiba",
    "Allées Seydou Nourou Tall",
    "Canal 4",
    "Hlm Guédiawaye",
    "Domaine de Guédiawaye",
    "Lycée Canada",
    "Tally Boubess",
    "Marché poissons",
    "Capa",
    "TP Cap Vert",
    "Relais Avenue Cheikh Anta Diop (Hôpital Fann)",
    "Scat Urbam",
    "Mairie grand Yoff",
    "Cité Cse",
    "Les deux voies de Sipres",
    "Les deux voies de Liberté 6",
    "Sicap rue 10",
    "Lycée Blaise Diagne",
    "Place ONU",
    "Travaux communaux",
    "Rue 22 prolongée",
    "Albert Sarraut"
]


def geocode_station(station_name):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {"address": station_name + ", Sénégal", "key": API_KEY}

    response = requests.get(base_url, params=params)
    data = response.json()

    if data["status"] == "OK" and data.get("results"):
        for result in data["results"]:
            # Vérifier si le résultat appartient au Sénégal
            if "Senegal" in result.get("formatted_address", ""):
                location = result["geometry"]["location"]
                latitude = location["lat"]
                longitude = location["lng"]
                return latitude, longitude

    return None


# Géocodage de toutes les stations et affichage des coordonnées
for station in stations:
    coordinates = geocode_station(station)
    if coordinates:
        latitude, longitude = coordinates
        print(f"{station}: Latitude = {latitude}, Longitude = {longitude}")
    else:
        print(f"{station}: Coordonnées non trouvées.")
