import requests

# Remplacez "VOTRE_CLE_API" par votre clé d'API Google Maps valide
API_KEY = "AIzaSyBJGDWHfSkHGw8rB7SefORqkSmHF7qX4x4"

# Liste des noms des stations de bus
stations = [
    "Terminus HLM Grand Yoff (Face Autoroute)",
    "Scat Urbam",
    "Liberté 6",
    "Derklé",
    "Liberté 4",
    "Rond Point Jet d'eau",
    "Bourguiba",
    "Grand Dakar",
    "Fass Médina",
    "Sham",
    "Avenue Blaise Diagne",
    "Terminus Lat Dior",
    "Terminus Yoff Village",
    "Aéroport LSS",
    "Route de Ngor",
    "Almadies",
    "Les Mamelles (Monument Renaissance)",
    "Ouakam",
    "Hôpital Fann",
    "UCAD/ENDSS",
    "Hôpital Abass Ndao",
    "Terminus Pétersen",
    "Terminus Guédiawaye",
    "Sapeur Pompier Guédiawaye",
    "Sonatel Guédiawaye",
    "Marché Peund Lansar",
    "Ecole Lansar (CEM Thiaroye Djiaddah Kao)",
    "Tally Bou Bess",
    "Bountou Pikine",
    "Autoroute",
    "Cité des Eaux",
    "Station Castor",
    "Jet d'eau",
    "Ecole Normale / Ecole Police",
    "Terminus Cheikh Anta Diop UCAD",
    "Terminus des Parcelles Assainies",
    "Foires",
    "VDN (voie de dégagement Nord)",
    "Permanence PDS",
    "Mermoz",
    "Tilène",
    "Poste Médina",
    "Crédit Foncier",
    "Camp Sapeur Pommier Parcelles",
    "Eglise",
    "Parcelles Assainies unité 17",
    "Marché Parcelles Assainies",
    "Parcelles Assainies unité 03",
    "Domaine Guédiawaya/Police Golf",
    "Pont Wakhinane Guediawaye",
    "PAI",
    "Tribunal Pikine Guédiawaye",
    "Station Tally Boumack",
    "Station Texaco",
    "Police Thiaroye",
    "Lycée Thiaroye",
    "Rond Point Thiaroye",
    "Terminus Poste Thiaroye",
    "Terminus Marché Boubess",
    "Lycée Limamoulaye",
    "Hôpital Roi Bédouin",
    "Préfecture Police Guédiawaye",
    "Rue 10",
    "Cité Lobatt Fall",
    "Colobane",
    "Central Park les Quatre C",
    "Grande Mosquée de Dakar",
    "Terminus Hamo VI",
    "Arrêt Ndial Mbaye",
    "Cité des enseignants",
    "Croisement Béthio",
    "Golf",
    "Fadia",
    "Case Ba",
    "Croisement Cambèrene",
    "Patte D'oie",
    "RTS",
    "Cité Nations Unis (Cambérène)",
    "Croisement 22",
    "Police Parcelle",
    "Pont Sénégal Emergent",
    "Deux voies de liberté 6",
    "Avenue Cheikh Anta Diop (UCAD)",
    "Avenue Blaise Diange",
    "Gadaye",
    "Tounal Baye Laye",
    "Tounal Serigne Assane",
    "Stade Ndiarème",
    "Deux voies Notaires",
    "Stade Amadou Barry",
    "Station Canada",
    "Cinéma U3",
    "Grand Yoff",
    "Camp Pénal",
    "Liberté 3,4,5,6",
    "Niary Tally",
    "Centre de Bob",
    "Terminus Colobane",
    "Terminus Texaco",
    "Tally Icotaf",
    "Marché Grand Yoff",
    "Rond Point Liberté 6",
    "Sacré coeur",
    "Collège Sacré Coeur",
    "Baobab",
    "Lycée Kennedy",
    "Monument",
    "Terminus Sham",
    "Guédiawaye",
    "Daroukhane",
    "Corniche Guédiawyae",
    "Hamo 4,5,6",
    "Deux Boulangeries Guediawaye",
    "Marche Jeudi Corniche",
    "Centre sauvegarde",
    "CEM Canada",
    "Marché Zing",
    "Castor",
    "HLM",
    "Marché Bou Bess",
    "Croisement Marché Sham",
    "Hôpital Dalal Jamm",
    "Pharmacie Golf",
    "Nord Foire",
    "Cité SIPRES",
    "Score liberté",
    "Sicap rue 10",
    "Zone B",
    "Lycée Blaise Diagne",
    "Canal UCAD",
    "Croisement Dioumadji",
    "Parcelles Assainies unité 22",
    "Champ Sapeur Pommier Parcelles",
    "Yoff Village",
    "Route de L'Aéroport",
    "Virage Ngor",
    "Terminus Ngor Village",
    "Pétersen",
    "SCOA YARAH",
    "Pont Colobane",
    "Tally Boumack",
    "Guédiawaye (Station Touré)",
    "Guédiawaye (Tournal Serigne Assane)",
    "Cité des Enseignants (Guédiawaye)",
    "Lycée des Parcelles Aissainies",
    "Rond Point case Ba",
    "Pont Aliou Sow",
    "Marché Grand-Yoff",
    "Hôpital de Grand Yoff (CTO)",
    "Université Bourguiba",
    "Jet d\"eau",
    "Ecole Normale /Ecole Police",
    "Centre de Transfusion Sanguine",
    "Terminus Diamalaye",
    "Front de Terre",
    "Gueule Tapée",
    "Agence Sonatel Médina",
    "Terminus Grand Mbao",
    "Diamaguène",
    "Agence Sonatel Thiaroye",
    "Station Cité Lobat Fall",
    "Poste Agence Malick Sy",
    "Guédiawaye Madial",
    "Guédiawaye(Station Touré)",
    "Police Pikine",
    "Marché Poissons",
    "Yarakh",
    "Capa",
    "Police bel air",
    "Pont Malick SY",
    "Pompier",
    "Gare de Pétersen",
    "Police Corniche Guédiawaye",
    "Hamo",
    "Hamo 4",
    "Parcelles Assainies Unité 26",
    "Foire",
    "Ancienne Piste",
    "Terminus Ouakam",
    "Thiaroye (C.D.Yeumbeul Sud)",
    "Tally Diallo",
    "Stade Alassane Djigo(Sadika)",
    "Complexe L.S. Senghor",
    "Pont EMG",
    "Terminus Ouakam Cité Avion",
    "Terminus Ouakam Bayé",
    "ENEA Aouakam",
    "Ecole des Officiers de la Gendarmerie",
    "Rond Point Ecole Normale",
    "VDN ( voie de dégagement Nord)",
    "Cap des buches",
    "Poste Thiaroye",
    "Petit Mbao",
    "Sicap Mbao",
    "Keur Mbaye Fall",
    "Terminus Grand Mbao Extention",
    "Terminus Guédiawaye Notaire",
    "Pikine Rue 10",
    "Collège Hyacinthe Thiandoum",
    "Stade Demba Diop",
    "Sadanga-Ponty",
    "Gare Lat Dior",
    "Yoff",
    "Rond Point Sénégal Emergent",
    "Avenue bourguiba",
    "Centre Douta SECK",
    "Sandaga",
    "Cité Serigne Mansour (Rufisque)",
    "Sonadis Rufisque",
    "Plateau(Rufisque)",
    "Rufsa",
    "Mbao",
    "Tivaouane Diack Sao",
    "Terminus Gadaye",
    "Tournal Baye Laye",
    "Tournal Serigne Assane",
    "Sapeur Pompier",
    "Arrêt dial Mbaye",
    "Séras de Yarakh",
    "Route du Front de Terre",
    "Boulangerie Jaune",
    "Gendarmerie Ouakam",
    "Mamelles",
    "Terminus Malika",
    "Yeumbeul",
    "Texaco",
    "Plan Jaxaay 1",
    "Deux voies keur Massar",
    "Station Keur Massar",
    "Hôpital keur Massar",
    "Arrêt Tenba Boune",
    "Route de BOUNE",
    "Croisement Yeumbeul",
    "Djouma Layenne",
    "Thiaroye (Thierno Ndiaye)",
    "Thiaroye Tally Diallo",
    "Ecole IACOM de Pikine",
    "Terminus Gare des beaux Maraîchers",
    "Eglise Bountou Pikine",
    "Malika",
    "Mbeubeuss",
    "Terminus Keur Massar",
    "Lac Rose",
    "Croisement Niague",
    "Ndiakhirate",
    "Route Des Niayes",
    "Route Nationale 1 (RN1)",
    "Bargny",
    "Diamniadio",
    "Hôpital Des Enfants Diamniadio",
    "Sébikotane",
    "Fass MBAO",
    "SIPS",
    "Sotiba",
    "LGI Mbao",
    "Croisement Fass Mbao",
    "Croisement Keur Massar",
    "Entrée Rufisque",
    "Terminus Rufisque",
    "Terminus Keur Massar Aladji Pathé",
    "Route Nationale 1(RN1)",
    "Cafétaria",
    "Avenue Elhadji Malick Sy",
    "Terminus Liberté 6",
    "Rond Point Cite Lobatt Fall",
    "Plateau (Rufisque)",
    "Gouye Mouride (Rufique)",
    "Terminus Fass Mbao Rail ba",
    "Parc Hann",
    "Agence le Soleil",
    "Service des Mines",
    "Terminus Stade Léopold Senghor",
    "Lycée des Parcelles Assainies",
    "Domaine Guédiawaye/Police Golf",
    "Ecole Keur Pauline",
    "Clinique Lansar",
    "Thiaroye(Thierno Ndiaye)",
    "Marché Yeumbeul",
    "MTOA Keur Massar",
    "Rufisque",
    "Terminus Bargny Guedj",
    "Rond Point Keur Massar",
    "Ngor",
    "Terminus Mamelles (Pharmacie Mamelles)",
    "Terminus Gueule Tapée Penc Mi",
    "Terminus Hôpital Youssou Mbargane (Rufisque)",
    "Cambérène",
    "Terminus Castor (Rufisque)",
    "Collège Serigne Cheikh Anta Mbacké (ex canada)",
    "Terminus Thiawlène (Rufisque)",
    "keur Massar",
    "Terminus Jaxaay 2",
    "Terminus Gorom I",
    "Gorom II",
    "Bambilor",
    "Noflaye",
    "Sangalkam",
    "Ndiakhiraate",
    "Keur Ndiaye Lo",
    "Pont Foire",
    "Terminus Yoff Frigo",
    "Terminus Ouakam Boutique Diallo",
    "Station Yeumbeul",
    "Ben Barack",
    "Sébikhotane",
    "Parcelles Assainies",
    "Croisement Tivaouane Peulh",
    "Tivaouane Peulh",
    "Terminus Tivaouane Peulh",
    "Tournal Serigne Assane (Guédiawaye)",
    "Hôpital Roi Baudouin",
    "Brioche Dorée Guédiawaye",
    "Cité Pénitentiaire",
    "Terminus Keur Massar (Maison de la Femme)",
    "Point E",
    "Relais",
    "Canal 4",
    "Terminus Cité Claudel",
    "Tribunal Pikine",
    "Hôpital Thiaroye",
    "Stade Galandou Diouf",
    "Croisement Rufisque",
    "Hôpital Youssou Mbarguane",
    "Pont Autoroute à péage",
    "Poste Courant",
    "Kounoune",
    "Terminus Kounoune (Cité Cardinal Thiandoum)",
    "Niakoul Rap",
    "Niague",
    "Terminus Lac Rose",
    "Terminus cité SOCABEG",
    "Cité Pénitentiare",
    "Malika (Cité Sonatel)",
    "Mariste",
    "Terminus Sud Foire",
    "Forêt classée de Mbao",
    "Terminus Cité Administration Pénitentiaire",
    "Terminus Rufisque Cité Taco",
    "Diouti-ba (Daral Rufisque)",
    "Cap des biches",
    "Senelec Castor",
    "Dieuppeul",
    "Terminus Liberté 5",
    "Thiaroye gouy ga",
    "Police Golf",
    "Cité Fadia Guentaba",
    "Police Parcelles Assainies",
    "Préfecture Guédiawaye",
    "Cité Gadaye",
    "VDN3",
    "Malika/Mer",
    "Parcelles Assainies Unité 15 16",
    "Ecole Fadial",
    "Caserne Sapeur Pompier",
    "CEM Cheikh Anta Mbacké (ex Canada)",
    "Croisement Tally Diallo",
    "Malika Montagne Mbeubeuss",
    "Gendarmerie Keur Massar",
    "Poste de Santé Niacoul rap",
    "Terminus Darou Thioub",
    "Hôpital Sicap Mbao",
    "Mbédou Fass",
    "Tournal Yeumbeul",
    "Cimetière Keur Massar",
    "Tivaouane Peulh Darou Salam APIX",
    "Terminus Cité Taw Feex Tivaouane Peulh",
    "Cité Comico Yeumbeul",
    "Boune",
    "Médina",
    "Terminus Gare Lat Dior",
    "Grand Yoff Bassin",
    "Hôpital Grand Yoff (Sétéwo)",
    "Plan Jaxaay 2"
]



def geocode_station(station_name):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {"address": station_name + ", Sénégal", "key": API_KEY}

    response = requests.get(base_url, params=params)
    data = response.json()

    if data["status"] == "OK" and data.get("results"):
        for result in data["results"]:
            # Vérifier si le résultat appartient au Sénégal
            if "Senegal" in result.get("formatted_address", ""):
                location = result["geometry"]["location"]
                latitude = location["lat"]
                longitude = location["lng"]
                return latitude, longitude

    return None


# Géocodage de toutes les stations et affichage des coordonnées
for station in stations:
    coordinates = geocode_station(station)
    if coordinates:
        latitude, longitude = coordinates
        print(f"{station}: Latitude = {latitude}, Longitude = {longitude}")
    else:
        print(f"{station}: Coordonnées non trouvées.")
