INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 1', 'Parcelles Assainies - Corniche (U 10-9-15) - Dior - Acapes - Dispensaire Norade - Passage entre U22 et U24 - Marché Grand-Médine - VDN - Relais - Avenue Cheikh Anta Diop - Avenue Blaise Diagne - Avenue Jean Jaurès - Avenue André Peytavin - Avenue George Pompidou - Place de l’Indépendance - Allées Canard - Esso Port - Embarcadère - Place Leclerc');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 4', 'Liberté 5 - Place Leclerc - Terminus Dieuppeul - Cité Derklé - Khar Yalla - Cité Marine - CEG Dieuppeul 3 - Camp Sapeurs-Pompiers - Cité Sacré Cœur - Collège Sacré Cœur - Sicap Karack - Avenue Bourguiba - Dial Diop ex rue 10 - Point E - HLM Fass - Canal Gueule Tapée - Avenue Blaise Diagne - Avenue Jean Jaurès - Boulevard de la République - Avenue Léopold Sédar Senghor - Allées Canard-Esso Port Embarcadère - Terminus Leclerc');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 7', 'Ouakam - Palais 2 - Terminus Ouakam - Cité Assemblée - Comico - Av Cheikh Anta Diop (route de Ouakam) - avenue Blaise Diagne - avenue Jean Jaurès - avenue André Peytavin - Avenue Georges Pompidou - Place de l’Indépendance - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais de Justice');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 8', 'Aéroport LSS - Palais 2 - Terminus Aéroport - Cité Asecna - Yoff Village - Stade Léopold Sédar Senghor - Patte d’Oie - Grand Yoff - Cité des Eaux - Avenue Bourguiba - Rue Dial Diop (ex rue 10) - Zone B - Rocade Fann Bel Air (Point E) - Avenue Cheikh Anta Diop (Cité Universitaire) - Avenue Blaise Diagne - Avenue Jean Jaurès - Bld de la République - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais de Justice');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 9', 'Liberté 6 - Palais 2 - Liberté 6 - Sacré Cœur - Terminus Dieuppeul - Allées Ababacar Sy - Rondpoint Jet d’Eau - Allées Cheikh Sidate (Niary Tally) - Eglise Sainte Thérèse - Avenue Dial Diop (ex rue 10) - Bld Général De Gaule - Avenue Malick Sy - Avenue Blaise Diagne - Avenue Jean Jaurès - Avenue André Peytavin - Avenue Pompidou - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais 2');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 10', 'Liberté 5 - Palais 2 - Terminus Dieuppeul - Cité Derklé - Khar Yalla - Cité Marine - CEG Dieuppeul 3 - Eglise Martyrs de l’Ouganda (rue 11 x P) - Stade Marius Ndiaye - Avenue Bourguiba - Relais - Avenue Cheikh Anta Diop - Rue Aimé Césaire - Corniche Ouest - Village Artisanal de Soumbédioune - Prison Central - Bld de la République - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais 2');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 13', 'Liberté 5 - Palais 2 - Terminus Dieuppeul - Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée) - Station Castors - Cité Port - Lycée Kennedy - Bld Général De Gaule - Allées Papa Guèye Fall - Avenue Faidherbe - Esso Port - Place de l’Indépendance - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais 2');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 18', 'Dieuppeul - Centre-ville - Dieuppeul - Terminus Dieuppeul - Cité Derklé - Khar Yalla - Cité Marine - Avenue Cheikh Ahmadou Bamba (ex rue 13 Prolongée) - Station Castors - Cité Port - Rocade Fann Bel Air - Colobane - Police Bel Air - Grand Moulin de Dakar - Quai de pêche - Esso Port - Place de l’Indépendance - Avenue Georges Pompidou - Avenue André Peytavin - Route de la Corniche - Avenue Malick Sy - Rue 6 - Gueule Tapée - Lycée Delafosse - Avenue Cheikh Anta Diop - Ecole Normale Supérieure - Avenue Bourguiba - Rond-Point Jet d’eau - Allées Ababacar Sy - Terminus Dieuppeul');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 20', 'Dieuppeul - Centre-ville - Dieuppeul - Terminus Dieuppeul - Allées Ababacar Sy - Jet d’eau - Avenue Bourguiba - Ecole Police (Relais) - Avenue Cheikh Anta Diop - Hôpital Fann - Cité Universitaire - Lycée Delafosse - HLM Gueule Tapée - Rue 6 - Avenue Malick Sy - Corniche Ouest - Avenue Peytavin - Avenue Pompidou - Place de l’Indépendance Esso Port - Bld de l’Arsenal - Central Bel Air (MTOA) - Grands Moulin de Dakar - Police Bel Air - Colobane - Angle Mousse - Avenue Cheikh Ahmadou Bamba - Station Castors - Cité Marine Khar Yalla - Cité Derklé - Terminus Dieuppeul');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 23', 'Parcelles Assainies - Palais 1 - Terminus des Parcelles - Ecole Dior - Cités Diamalaye - Hlm Grand Médine - Reprise Route du Terminus - Eglise - Route des Niayes - Echangeur du Stade Léopold Sédar Senghor (Amitié) - Cité Keur Khadim - Camp Pénal - Route du Front de Terre - Cité des Eaux - Avenue Bourguiba - Relais - Avenue Cheikh Anta Diop - (Route de Ouakam) - Marché SAHM - Gueule Tapée - Rue 6 - Avenue Malick Sy - Avenue Blaise Diagne - Avenue Jean Jaurès - Bld de la République - Avenue Léopold Sédar Senghor - Hôpital Principal - Avenue Nelson Mandela - Hôpital Le Dantec - Palais de Justice');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 121', 'Scat Urbam - Leclerc - Terminus Scat Urban - Mairie grand Yoff - Cité Cse - Les deux voies de Sipres - Les deux voies de Liberté 6 - Collège Sacré Cœur - Sicap rue 10 - Lycée Blaise Diagne - Place ONU - Canal 4 - HLM Fass - Travaux communaux - rue 22 prolongée - Rts - Allées Papa Guèye Fall - Avenue Faidherbe - Place de l’indépendance - Albert Sarraut - Terminus Leclerc');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 2', 'Daroukhane - Place Leclerc - Daroukhane - Corniche-Hamo - Terminus Guédiawaye - Marché Sahm - Ecole Canada - Route des Niayes - Tally Boumack (route de l’Ouest) - Route Nationale n° 1 - Autoroute - Cité des Eaux - Avenue Bourguiba - Avenue Cheikh Ahmadou Bamba (ex Rue 13 Prolongée) - Bld Général De Gaule - Rue 25 - Avenue Blaise Diagne - Avenue Jean Jaurès - Avenue Georges Pompidou - Place de l’Indépendance - Esso Port - Leclerc');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 5', 'Guédiawaye - Palais 1 - Terminus Guédiawaye - Route de la Corniche - Cité des Enseignants - Maison du PAI - Cité Hlm - Golf - Route des Niayes - Police de Parcelles Assainies - Pont du Stade Léopold Sédar Senghor (Echangeur) - Patte d’Oie - Autoroute - Passage Cyrnos - Avenue Lamine Guèye - Avenue André Peytavin - avenue Jean Jaurès - Bld de la République - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais de Justice 1');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 6', 'Cambérène 2 - Palais 2 - Cambérène 2 - Cambérène village - Case - Route des Niayes - Police des Parcelles Assainies - Marché Grand-Médine - Cité Keur Damel - VDN Sipres - Camp Pénal - Derklé - Liberté 5 - Allées Khalifa Ababacar Sy - Jet d’Eau - Niary Tally - Enam - Bld Général De Gaule - Allées Papa Guèye Fall - Avenue Faidherbe - Avenue Lamine Guèye - Avenue André Peytavin - Avenue Jean Jaurès - Bld de la République - Avenue Nelson Mandela - Palais 2');

INSERT INTO Itineraire (Ligne, Route) VALUES('Ligne 11', 'Keur Massar - Lat Dior - Terminus Keur Massar - Parcelles Assainies (keur Massar) Route de Boune - Fass Mbao - Diamaguène - Thiaroye/mer - Croisement Pikine - Route Nationale - Autoroute - Corniche des Hlm - Colobane - Caisse de sécurité sociale - Bd Général De Gaule (Centenaire) - RTS - Rond Point Poste Médina - Blaise Diagne - Sandaga - Terminus Lat-Dior');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 12', 'Guédiawaye - Palais 1 - Terminus Guédiawaye - Cité des Enseignants - Maison du PAI - Hlm Guédiawaye - Domaine de Guédiawaye - Lycée Canada - Route des Niayes - Tally Boubess - Marché poissons - Route de Rufisque - Capa - TP Cap Vert - Cité des Eaux - Avenue Bourguiba - Relais Avenue Cheikh Anta Diop (Hôpital Fann) - Avenue Blaise Diagne - Avenue Jean Jaurès - Bld de la République - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais de Justice');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 15A & 15B', 'Rufisque - Palais 1 - Terminus Rufisque - Mosquée Keuri Kaw - Sortie Rufisque (Dioukoul) - Sicap Mbao - Diamaguène - Croisement Pikine - Route de Rufisque - SCOA - SONACOS - Bld de l’Arsenal - Esso Port - Place de l’Indépendance - Avenue Léopold Sédar Senghor - Avenue Nelson Mandela - Palais 1');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 16A', 'Malika - Palais 1 - Terminus Malika - Yeumbeul - Tally Diallo - Icotaf - Cité Lobatt Fall - Rond-point Lobatt Fall - Autoroute - Colobane - Rond-point Colobane - Place Bakou - Cfao Technologies - Cyrnos - Arsenal - Place de l’Indépendance - Palais de justice 1');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 16B', 'Malika - Palais 1 - Terminus Malika - Station Keur Massar - Croisement Keur Massar - LGI Mbao - Diamaguène - Thiaroye - Sips - Sotiba (seras) - Yarakh - Capa Virmaud - Place Bakou - (Scoa) - Police Bel Air - Bel Air - GMD - Sofrigal (môle 8) - Cyrnos (sur le pont) - Caserne Sapeurs Pompiers - Avenue Lamine Guèye (Sandaga) - Avenue André Peytavin - Avenue Jean Jaurès - Boulevard de la République - Avenue Léopold Sédar Senghor (Roume) - Hôpital Principal - Assemblée Nationale - Hôpital Le Dantec - Palais 1');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 208', 'Bayakh - Rufisque - Gorom 01- Gororm 02 - Bambilor - Noflaye - Sangalkam - Keur Ndiaye Lo - Rufisque');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 213', 'Rufisque - Dieuppeul - Gare de Rufisque - HLM SIPRES - ZAC Mbao - Grand Mbao - Stade Mbao - Petit Mbao - Croisement Petit Mbao - RN1 - poste Thiaroye - péage - sortie Cambérène - Patte d’Oie -Marche Grand Yoff - Police Grand Yoff - Rond-Point Liberté 6 - Terminus Dieuppeul');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 217', 'Thiaroye - Ouakam - Dépôt Thiaroye - police Thiaroye - Route des Niayes - Pikine - Canada Golf Fadia - Case bi - Croisement 22 - Eglise - Terminus parcelles Assainies - Dior Centre Bceao - Route cimetière Yoff - Route de L’Aéroport - Ngor– route des Almadies - Mamelles - Marché Ouakam - Terminus Ouakam');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 218', 'Thiaroye - Aéroport LSS - Dépôt Thiaroye - Route Nationale N° 1 - Pikine - patte d’oies - Foire - VDN - Sipres - ancienne piste - Ouakam - marché Ouakam - terminus Ouakam - route des mamelles - route des Almadies - Ngor - Terminus aéroport LSS');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 219', 'Daroukhane - Ouakam - Daroukhane - marché Ndiarème - deux voies Pikine Notaire - Terminus Guédiawaye - Stade Amadou Barry - Marché Sham - Marché Jeudi corniche - Croisement Béthio - Fadia - Case bi - Pont Sénégal 92 - Collège Hyacinthe Thiandoum - Deux voies liberté 6 - Ancienne Piste - Hôpital militaire de Ouakam - Comico - Cité Asecna - Cité Assemblée - Terminus Ouakam');

INSERT INTO Itineraire (Ligne, Route) VALUES('Ligne 220', 'Rufisque - Guédiawaye - Terminus Rufisque - Djoutiba - HLM Rufisque - SIPRES- SEDIMA - Lycée Jaxaay-2 voies - Jaxaay - Station Keur Massar - Terminus Malika - Malika Plage - Sortie Autoroute - Serigne Assane - Lycée Limamoulaye - Terminus Guediawaye');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 221', 'Gadaye - Almadies - Cité Gadaye (Filaos) - Corniche Daroukhane - Hamo 6 - Arrêt Dial Mbaye - PAI - Dalal Diam - Case - Police PA - Pont Sénégal emergent - Route de l’aéroport - Yoff Tonghor - Cite Asecna - Rond-point Ngor - Ngor village - Almadies');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 227', 'Terminus Keur Massar - Terminus Parcelles - Terminus Keur Massar - Station Keur Massar - Hôpital Keur Massar - Keur Massar - Terminus Malika - Malika plage - Sortie autoroute - Stade amadou Barry - CES Canada - Pharmacie Golf - Fadia - Case bi - Croisement 22 - Eglise PA - Terminus Parcelles');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 228', 'Terminus Rufisque - Yenne - Terminus Rufisque - ville de Rufisque - Bargny - Diamniadio Yenne.');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 232', 'Baux Maraichers - Aéroport LSS - Baux Maraichers - Yarakh - Cafétéria - Hann Maristes - Cours Sainte Marie de Hann - Usine des eaux - Front de terre - Khar Yalla - Rond-Point Liberté 6 - deux voies vers Camp Leclerc - Foire - Itinéraire ligne 8 - Terminus Aéroport LSS');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 233', 'Baux Maraichers - Palais 1 - Baux maraichers - RN1 - Croisement Cambérène - Mariste- Castors - Itinéraire ligne13 - Rond-point maison PS - Hampathé Ba - Cité Claudel - Immeuble Dieze - Rue 6- Malick Sy - Poste Médine - Ave Blaise Diagne - Avenue Peytavin - Ponty - place de l’Indépendance - Hôpital Principal - hôpital Le Dantec - Palais 1');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 234', 'Jaxaay - Leclerc - Mosquée Niakoul Rab - Ecole Panthéon - 2 voies Jaxaay - Station Keur Massar - Croisement Keur Massar - Fass Mbao - Diamagueune - Poste Thiaroye - Autoroute - Péage - AIBD');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 401', 'Ouakam ↔ Sphère - Terminus Ouakam - Mamelles - Croisement Almadies - Ngor- Yoff - Rte de l’Aéroport - Foire - VDN- Direction Générale DDD - Rond-Point JVC- Rond-Point Liberté 6 - Itinéraire 213 - Police Grand Yoff - Pharmacie Patte d’Oie - Terminus Sphère');

INSERT INTO Itineraire (Ligne, Route) VALUES ('Ligne 402', 'Ouakam ↔ Cité Gadaye - Terminus Ouakam - Marché Ouakam - Carrefour Yarakh - Poste Mamelles - Almadies - Phare des Mamelles - corniche Ouest - Yoff APECSY - Cité Gadaye');
